// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "invntt_tomont.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic invntt_tomont::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic invntt_tomont::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> invntt_tomont::ap_ST_fsm_state1 = "1";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state2 = "10";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state3 = "100";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state4 = "1000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state5 = "10000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state6 = "100000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> invntt_tomont::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_1 = "1";
const sc_lv<32> invntt_tomont::ap_const_lv32_2 = "10";
const sc_lv<1> invntt_tomont::ap_const_lv1_1 = "1";
const sc_lv<1> invntt_tomont::ap_const_lv1_0 = "0";
const sc_lv<32> invntt_tomont::ap_const_lv32_3 = "11";
const sc_lv<32> invntt_tomont::ap_const_lv32_4 = "100";
const sc_lv<32> invntt_tomont::ap_const_lv32_5 = "101";
const sc_lv<32> invntt_tomont::ap_const_lv32_8 = "1000";
const sc_lv<9> invntt_tomont::ap_const_lv9_1 = "1";
const sc_lv<10> invntt_tomont::ap_const_lv10_0 = "0000000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_7 = "111";
const sc_lv<32> invntt_tomont::ap_const_lv32_9 = "1001";
const sc_lv<9> invntt_tomont::ap_const_lv9_0 = "000000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_100 = "100000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_6 = "110";
const sc_lv<8> invntt_tomont::ap_const_lv8_0 = "00000000";
const sc_lv<2> invntt_tomont::ap_const_lv2_0 = "00";
const sc_lv<32> invntt_tomont::ap_const_lv32_FFFFFFFF = "11111111111111111111111111111111";
const sc_lv<23> invntt_tomont::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<32> invntt_tomont::ap_const_lv32_3802001 = "11100000000010000000000001";
const sc_lv<55> invntt_tomont::ap_const_lv55_7FFFFFFF801FFF = "1111111111111111111111111111111100000000001111111111111";
const sc_lv<32> invntt_tomont::ap_const_lv32_20 = "100000";
const sc_lv<32> invntt_tomont::ap_const_lv32_37 = "110111";
const sc_lv<9> invntt_tomont::ap_const_lv9_100 = "100000000";
const sc_lv<49> invntt_tomont::ap_const_lv49_A3FA = "1010001111111010";
const bool invntt_tomont::ap_const_boolean_1 = true;

invntt_tomont::invntt_tomont(sc_module_name name) : sc_module(name), mVcdFile(0) {
    zetas_U = new ntt_1_zetas("zetas_U");
    zetas_U->clk(ap_clk);
    zetas_U->reset(ap_rst);
    zetas_U->address0(zetas_address0);
    zetas_U->ce0(zetas_ce0);
    zetas_U->q0(zetas_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( a_addr_reg_550 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( a_addr_16_reg_555 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( a_addr55_reg_584 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( zext_ln87_fu_288_p1 );

    SC_METHOD(thread_a_address1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( a_addr_16_reg_555 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( zext_ln88_3_fu_312_p1 );
    sensitive << ( zext_ln96_1_fu_422_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_a_ce1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_a_d0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( add_ln88_1_fu_331_p2 );
    sensitive << ( t_12_fu_396_p1 );
    sensitive << ( t_10_fu_481_p1 );

    SC_METHOD(thread_a_we0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_add_ln19_2_fu_380_p2);
    sensitive << ( sext_ln90_1_fu_352_p1 );
    sensitive << ( sext_ln19_12_fu_376_p1 );

    SC_METHOD(thread_add_ln19_fu_465_p2);
    sensitive << ( sext_ln19_9_fu_461_p1 );
    sensitive << ( sext_ln96_1_fu_437_p1 );

    SC_METHOD(thread_add_ln84_1_fu_252_p2);
    sensitive << ( len_0_reg_114 );
    sensitive << ( trunc_ln84_fu_248_p1 );

    SC_METHOD(thread_add_ln84_fu_323_p2);
    sensitive << ( zext_ln83_reg_500 );
    sensitive << ( zext_ln84_1_reg_537 );

    SC_METHOD(thread_add_ln86_fu_233_p2);
    sensitive << ( zext_ln83_reg_500 );
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_add_ln87_fu_283_p2);
    sensitive << ( zext_ln77_reg_493 );
    sensitive << ( trunc_ln87_fu_279_p1 );

    SC_METHOD(thread_add_ln88_1_fu_331_p2);
    sensitive << ( a_q0 );
    sensitive << ( a_q1 );

    SC_METHOD(thread_add_ln88_2_fu_307_p2);
    sensitive << ( zext_ln77_reg_493 );
    sensitive << ( add_ln88_fu_301_p2 );

    SC_METHOD(thread_add_ln88_fu_301_p2);
    sensitive << ( zext_ln88_fu_297_p1 );
    sensitive << ( trunc_ln88_fu_293_p1 );

    SC_METHOD(thread_add_ln96_fu_417_p2);
    sensitive << ( zext_ln77_reg_493 );
    sensitive << ( zext_ln96_fu_413_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln95_fu_401_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln95_fu_401_p2 );

    SC_METHOD(thread_empty_55_fu_242_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( j_reg_126 );
    sensitive << ( add_ln86_fu_233_p2 );

    SC_METHOD(thread_icmp_ln84_fu_201_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_11_fu_191_p4 );

    SC_METHOD(thread_icmp_ln86_fu_274_p2);
    sensitive << ( zext_ln86_reg_532 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_icmp_ln95_fu_401_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_j_3_fu_407_p2);
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_j_4_fu_317_p2);
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_k_fu_210_p2);
    sensitive << ( k_4_fu_58 );

    SC_METHOD(thread_len_fu_221_p2);
    sensitive << ( len_0_reg_114 );

    SC_METHOD(thread_mul_ln19_2_fu_370_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( t_11_fu_360_p2 );

    SC_METHOD(thread_mul_ln19_2_fu_370_p2);
    sensitive << ( mul_ln19_2_fu_370_p1 );

    SC_METHOD(thread_mul_ln19_fu_455_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( t_9_fu_445_p2 );

    SC_METHOD(thread_mul_ln19_fu_455_p2);
    sensitive << ( mul_ln19_fu_455_p1 );

    SC_METHOD(thread_mul_ln90_fu_347_p0);
    sensitive << ( sext_ln86_reg_542 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_mul_ln90_fu_347_p1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( sub_ln89_fu_338_p2 );

    SC_METHOD(thread_mul_ln90_fu_347_p2);
    sensitive << ( mul_ln90_fu_347_p0 );
    sensitive << ( mul_ln90_fu_347_p1 );

    SC_METHOD(thread_mul_ln96_fu_431_p1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( sext_ln96_fu_427_p0 );

    SC_METHOD(thread_mul_ln96_fu_431_p2);
    sensitive << ( mul_ln96_fu_431_p1 );

    SC_METHOD(thread_sext_ln19_12_fu_376_p1);
    sensitive << ( mul_ln19_2_fu_370_p2 );

    SC_METHOD(thread_sext_ln19_9_fu_461_p1);
    sensitive << ( mul_ln19_fu_455_p2 );

    SC_METHOD(thread_sext_ln86_fu_270_p1);
    sensitive << ( zeta_fu_227_p2 );

    SC_METHOD(thread_sext_ln90_1_fu_352_p1);
    sensitive << ( mul_ln90_fu_347_p2 );

    SC_METHOD(thread_sext_ln96_1_fu_437_p1);
    sensitive << ( mul_ln96_fu_431_p2 );

    SC_METHOD(thread_sext_ln96_fu_427_p0);
    sensitive << ( a_q1 );
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_start_fu_258_p3);
    sensitive << ( trunc_ln84_fu_248_p1 );
    sensitive << ( empty_55_fu_242_p2 );
    sensitive << ( add_ln84_1_fu_252_p2 );

    SC_METHOD(thread_sub_ln89_fu_338_p2);
    sensitive << ( a_q1 );
    sensitive << ( t_reg_571 );

    SC_METHOD(thread_t_10_fu_481_p1);
    sensitive << ( trunc_ln_fu_471_p4 );

    SC_METHOD(thread_t_11_fu_360_p2);
    sensitive << ( trunc_ln18_2_fu_356_p1 );

    SC_METHOD(thread_t_12_fu_396_p1);
    sensitive << ( trunc_ln19_1_fu_386_p4 );

    SC_METHOD(thread_t_9_fu_445_p2);
    sensitive << ( trunc_ln18_fu_441_p1 );

    SC_METHOD(thread_tmp_10_fu_179_p3);
    sensitive << ( len_0_reg_114 );

    SC_METHOD(thread_tmp_11_fu_191_p4);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_tmp_fu_158_p3);
    sensitive << ( a_offset );

    SC_METHOD(thread_trunc_ln18_2_fu_356_p1);
    sensitive << ( mul_ln90_fu_347_p2 );

    SC_METHOD(thread_trunc_ln18_fu_441_p1);
    sensitive << ( mul_ln96_fu_431_p2 );

    SC_METHOD(thread_trunc_ln19_1_fu_386_p4);
    sensitive << ( add_ln19_2_fu_380_p2 );

    SC_METHOD(thread_trunc_ln84_fu_248_p1);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_trunc_ln87_fu_279_p1);
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_trunc_ln88_fu_293_p1);
    sensitive << ( j_0_reg_138 );

    SC_METHOD(thread_trunc_ln_fu_471_p4);
    sensitive << ( add_ln19_fu_465_p2 );

    SC_METHOD(thread_zeta_fu_227_p2);
    sensitive << ( zetas_q0 );

    SC_METHOD(thread_zetas_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln85_fu_216_p1 );

    SC_METHOD(thread_zetas_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_zext_ln77_fu_166_p1);
    sensitive << ( tmp_fu_158_p3 );

    SC_METHOD(thread_zext_ln83_fu_175_p1);
    sensitive << ( len_0_reg_114 );

    SC_METHOD(thread_zext_ln84_1_fu_266_p1);
    sensitive << ( start_fu_258_p3 );

    SC_METHOD(thread_zext_ln84_fu_187_p1);
    sensitive << ( j_reg_126 );

    SC_METHOD(thread_zext_ln85_fu_216_p1);
    sensitive << ( k_fu_210_p2 );

    SC_METHOD(thread_zext_ln86_fu_238_p1);
    sensitive << ( add_ln86_fu_233_p2 );

    SC_METHOD(thread_zext_ln87_fu_288_p1);
    sensitive << ( add_ln87_fu_283_p2 );

    SC_METHOD(thread_zext_ln88_3_fu_312_p1);
    sensitive << ( add_ln88_2_fu_307_p2 );

    SC_METHOD(thread_zext_ln88_fu_297_p1);
    sensitive << ( len_0_reg_114 );

    SC_METHOD(thread_zext_ln96_1_fu_422_p1);
    sensitive << ( add_ln96_fu_417_p2 );

    SC_METHOD(thread_zext_ln96_fu_413_p1);
    sensitive << ( j_1_reg_147 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln84_fu_201_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln86_fu_274_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln95_fu_401_p2 );
    sensitive << ( tmp_10_fu_179_p3 );

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "invntt_tomont_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_we0, "(port)a_we0");
    sc_trace(mVcdFile, a_d0, "(port)a_d0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, a_address1, "(port)a_address1");
    sc_trace(mVcdFile, a_ce1, "(port)a_ce1");
    sc_trace(mVcdFile, a_q1, "(port)a_q1");
    sc_trace(mVcdFile, a_offset, "(port)a_offset");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, zetas_address0, "zetas_address0");
    sc_trace(mVcdFile, zetas_ce0, "zetas_ce0");
    sc_trace(mVcdFile, zetas_q0, "zetas_q0");
    sc_trace(mVcdFile, zext_ln77_fu_166_p1, "zext_ln77_fu_166_p1");
    sc_trace(mVcdFile, zext_ln77_reg_493, "zext_ln77_reg_493");
    sc_trace(mVcdFile, zext_ln83_fu_175_p1, "zext_ln83_fu_175_p1");
    sc_trace(mVcdFile, zext_ln83_reg_500, "zext_ln83_reg_500");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln84_fu_187_p1, "zext_ln84_fu_187_p1");
    sc_trace(mVcdFile, zext_ln84_reg_509, "zext_ln84_reg_509");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, k_fu_210_p2, "k_fu_210_p2");
    sc_trace(mVcdFile, k_reg_517, "k_reg_517");
    sc_trace(mVcdFile, icmp_ln84_fu_201_p2, "icmp_ln84_fu_201_p2");
    sc_trace(mVcdFile, len_fu_221_p2, "len_fu_221_p2");
    sc_trace(mVcdFile, zext_ln86_fu_238_p1, "zext_ln86_fu_238_p1");
    sc_trace(mVcdFile, zext_ln86_reg_532, "zext_ln86_reg_532");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, zext_ln84_1_fu_266_p1, "zext_ln84_1_fu_266_p1");
    sc_trace(mVcdFile, zext_ln84_1_reg_537, "zext_ln84_1_reg_537");
    sc_trace(mVcdFile, sext_ln86_fu_270_p1, "sext_ln86_fu_270_p1");
    sc_trace(mVcdFile, sext_ln86_reg_542, "sext_ln86_reg_542");
    sc_trace(mVcdFile, a_addr_reg_550, "a_addr_reg_550");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, icmp_ln86_fu_274_p2, "icmp_ln86_fu_274_p2");
    sc_trace(mVcdFile, a_addr_16_reg_555, "a_addr_16_reg_555");
    sc_trace(mVcdFile, j_4_fu_317_p2, "j_4_fu_317_p2");
    sc_trace(mVcdFile, j_4_reg_561, "j_4_reg_561");
    sc_trace(mVcdFile, add_ln84_fu_323_p2, "add_ln84_fu_323_p2");
    sc_trace(mVcdFile, t_reg_571, "t_reg_571");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, j_3_fu_407_p2, "j_3_fu_407_p2");
    sc_trace(mVcdFile, j_3_reg_579, "j_3_reg_579");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, a_addr55_reg_584, "a_addr55_reg_584");
    sc_trace(mVcdFile, icmp_ln95_fu_401_p2, "icmp_ln95_fu_401_p2");
    sc_trace(mVcdFile, len_0_reg_114, "len_0_reg_114");
    sc_trace(mVcdFile, j_reg_126, "j_reg_126");
    sc_trace(mVcdFile, tmp_10_fu_179_p3, "tmp_10_fu_179_p3");
    sc_trace(mVcdFile, j_0_reg_138, "j_0_reg_138");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, j_1_reg_147, "j_1_reg_147");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, zext_ln85_fu_216_p1, "zext_ln85_fu_216_p1");
    sc_trace(mVcdFile, zext_ln87_fu_288_p1, "zext_ln87_fu_288_p1");
    sc_trace(mVcdFile, zext_ln88_3_fu_312_p1, "zext_ln88_3_fu_312_p1");
    sc_trace(mVcdFile, zext_ln96_1_fu_422_p1, "zext_ln96_1_fu_422_p1");
    sc_trace(mVcdFile, k_4_fu_58, "k_4_fu_58");
    sc_trace(mVcdFile, add_ln88_1_fu_331_p2, "add_ln88_1_fu_331_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, t_12_fu_396_p1, "t_12_fu_396_p1");
    sc_trace(mVcdFile, t_10_fu_481_p1, "t_10_fu_481_p1");
    sc_trace(mVcdFile, tmp_fu_158_p3, "tmp_fu_158_p3");
    sc_trace(mVcdFile, tmp_11_fu_191_p4, "tmp_11_fu_191_p4");
    sc_trace(mVcdFile, add_ln86_fu_233_p2, "add_ln86_fu_233_p2");
    sc_trace(mVcdFile, trunc_ln84_fu_248_p1, "trunc_ln84_fu_248_p1");
    sc_trace(mVcdFile, empty_55_fu_242_p2, "empty_55_fu_242_p2");
    sc_trace(mVcdFile, add_ln84_1_fu_252_p2, "add_ln84_1_fu_252_p2");
    sc_trace(mVcdFile, start_fu_258_p3, "start_fu_258_p3");
    sc_trace(mVcdFile, zeta_fu_227_p2, "zeta_fu_227_p2");
    sc_trace(mVcdFile, trunc_ln87_fu_279_p1, "trunc_ln87_fu_279_p1");
    sc_trace(mVcdFile, add_ln87_fu_283_p2, "add_ln87_fu_283_p2");
    sc_trace(mVcdFile, zext_ln88_fu_297_p1, "zext_ln88_fu_297_p1");
    sc_trace(mVcdFile, trunc_ln88_fu_293_p1, "trunc_ln88_fu_293_p1");
    sc_trace(mVcdFile, add_ln88_fu_301_p2, "add_ln88_fu_301_p2");
    sc_trace(mVcdFile, add_ln88_2_fu_307_p2, "add_ln88_2_fu_307_p2");
    sc_trace(mVcdFile, sub_ln89_fu_338_p2, "sub_ln89_fu_338_p2");
    sc_trace(mVcdFile, mul_ln90_fu_347_p0, "mul_ln90_fu_347_p0");
    sc_trace(mVcdFile, mul_ln90_fu_347_p1, "mul_ln90_fu_347_p1");
    sc_trace(mVcdFile, mul_ln90_fu_347_p2, "mul_ln90_fu_347_p2");
    sc_trace(mVcdFile, trunc_ln18_2_fu_356_p1, "trunc_ln18_2_fu_356_p1");
    sc_trace(mVcdFile, t_11_fu_360_p2, "t_11_fu_360_p2");
    sc_trace(mVcdFile, mul_ln19_2_fu_370_p1, "mul_ln19_2_fu_370_p1");
    sc_trace(mVcdFile, mul_ln19_2_fu_370_p2, "mul_ln19_2_fu_370_p2");
    sc_trace(mVcdFile, sext_ln90_1_fu_352_p1, "sext_ln90_1_fu_352_p1");
    sc_trace(mVcdFile, sext_ln19_12_fu_376_p1, "sext_ln19_12_fu_376_p1");
    sc_trace(mVcdFile, add_ln19_2_fu_380_p2, "add_ln19_2_fu_380_p2");
    sc_trace(mVcdFile, trunc_ln19_1_fu_386_p4, "trunc_ln19_1_fu_386_p4");
    sc_trace(mVcdFile, zext_ln96_fu_413_p1, "zext_ln96_fu_413_p1");
    sc_trace(mVcdFile, add_ln96_fu_417_p2, "add_ln96_fu_417_p2");
    sc_trace(mVcdFile, sext_ln96_fu_427_p0, "sext_ln96_fu_427_p0");
    sc_trace(mVcdFile, mul_ln96_fu_431_p1, "mul_ln96_fu_431_p1");
    sc_trace(mVcdFile, mul_ln96_fu_431_p2, "mul_ln96_fu_431_p2");
    sc_trace(mVcdFile, trunc_ln18_fu_441_p1, "trunc_ln18_fu_441_p1");
    sc_trace(mVcdFile, t_9_fu_445_p2, "t_9_fu_445_p2");
    sc_trace(mVcdFile, mul_ln19_fu_455_p1, "mul_ln19_fu_455_p1");
    sc_trace(mVcdFile, mul_ln19_fu_455_p2, "mul_ln19_fu_455_p2");
    sc_trace(mVcdFile, sext_ln19_9_fu_461_p1, "sext_ln19_9_fu_461_p1");
    sc_trace(mVcdFile, sext_ln96_1_fu_437_p1, "sext_ln96_1_fu_437_p1");
    sc_trace(mVcdFile, add_ln19_fu_465_p2, "add_ln19_fu_465_p2");
    sc_trace(mVcdFile, trunc_ln_fu_471_p4, "trunc_ln_fu_471_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

invntt_tomont::~invntt_tomont() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete zetas_U;
}

void invntt_tomont::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        j_0_reg_138 = j_4_reg_561.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_0_reg_138 = zext_ln84_reg_509.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_10_fu_179_p3.read()))) {
        j_1_reg_147 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_1_reg_147 = j_3_reg_579.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_10_fu_179_p3.read()))) {
        j_reg_126 = ap_const_lv10_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_274_p2.read()))) {
        j_reg_126 = add_ln84_fu_323_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_274_p2.read()))) {
        k_4_fu_58 = k_reg_517.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_4_fu_58 = ap_const_lv32_100;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln84_fu_201_p2.read(), ap_const_lv1_0))) {
        len_0_reg_114 = len_fu_221_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        len_0_reg_114 = ap_const_lv9_1;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln95_fu_401_p2.read()))) {
        a_addr55_reg_584 =  (sc_lv<10>) (zext_ln96_1_fu_422_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln86_fu_274_p2.read()))) {
        a_addr_16_reg_555 =  (sc_lv<10>) (zext_ln88_3_fu_312_p1.read());
        a_addr_reg_550 =  (sc_lv<10>) (zext_ln87_fu_288_p1.read());
        j_4_reg_561 = j_4_fu_317_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        j_3_reg_579 = j_3_fu_407_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln84_fu_201_p2.read(), ap_const_lv1_1))) {
        k_reg_517 = k_fu_210_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        sext_ln86_reg_542 = sext_ln86_fu_270_p1.read();
        zext_ln84_1_reg_537 = zext_ln84_1_fu_266_p1.read();
        zext_ln86_reg_532 = zext_ln86_fu_238_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        t_reg_571 = a_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        zext_ln77_reg_493 = zext_ln77_fu_166_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        zext_ln83_reg_500 = zext_ln83_fu_175_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zext_ln84_reg_509 = zext_ln84_fu_187_p1.read();
    }
}

void invntt_tomont::thread_a_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_address0 = a_addr55_reg_584.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        a_address0 = a_addr_16_reg_555.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_address0 = a_addr_reg_550.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_address0 =  (sc_lv<10>) (zext_ln87_fu_288_p1.read());
    } else {
        a_address0 = "XXXXXXXXXX";
    }
}

void invntt_tomont::thread_a_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        a_address1 =  (sc_lv<10>) (zext_ln96_1_fu_422_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        a_address1 = a_addr_16_reg_555.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        a_address1 =  (sc_lv<10>) (zext_ln88_3_fu_312_p1.read());
    } else {
        a_address1 = "XXXXXXXXXX";
    }
}

void invntt_tomont::thread_a_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void invntt_tomont::thread_a_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        a_ce1 = ap_const_logic_1;
    } else {
        a_ce1 = ap_const_logic_0;
    }
}

void invntt_tomont::thread_a_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_d0 = t_10_fu_481_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        a_d0 = t_12_fu_396_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        a_d0 = add_ln88_1_fu_331_p2.read();
    } else {
        a_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void invntt_tomont::thread_a_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        a_we0 = ap_const_logic_1;
    } else {
        a_we0 = ap_const_logic_0;
    }
}

void invntt_tomont::thread_add_ln19_2_fu_380_p2() {
    add_ln19_2_fu_380_p2 = (!sext_ln90_1_fu_352_p1.read().is_01() || !sext_ln19_12_fu_376_p1.read().is_01())? sc_lv<56>(): (sc_bigint<56>(sext_ln90_1_fu_352_p1.read()) + sc_bigint<56>(sext_ln19_12_fu_376_p1.read()));
}

void invntt_tomont::thread_add_ln19_fu_465_p2() {
    add_ln19_fu_465_p2 = (!sext_ln19_9_fu_461_p1.read().is_01() || !sext_ln96_1_fu_437_p1.read().is_01())? sc_lv<56>(): (sc_bigint<56>(sext_ln19_9_fu_461_p1.read()) + sc_bigint<56>(sext_ln96_1_fu_437_p1.read()));
}

void invntt_tomont::thread_add_ln84_1_fu_252_p2() {
    add_ln84_1_fu_252_p2 = (!trunc_ln84_fu_248_p1.read().is_01() || !len_0_reg_114.read().is_01())? sc_lv<9>(): (sc_biguint<9>(trunc_ln84_fu_248_p1.read()) + sc_biguint<9>(len_0_reg_114.read()));
}

void invntt_tomont::thread_add_ln84_fu_323_p2() {
    add_ln84_fu_323_p2 = (!zext_ln84_1_reg_537.read().is_01() || !zext_ln83_reg_500.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln84_1_reg_537.read()) + sc_biguint<10>(zext_ln83_reg_500.read()));
}

void invntt_tomont::thread_add_ln86_fu_233_p2() {
    add_ln86_fu_233_p2 = (!zext_ln83_reg_500.read().is_01() || !j_reg_126.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln83_reg_500.read()) + sc_biguint<10>(j_reg_126.read()));
}

void invntt_tomont::thread_add_ln87_fu_283_p2() {
    add_ln87_fu_283_p2 = (!zext_ln77_reg_493.read().is_01() || !trunc_ln87_fu_279_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln77_reg_493.read()) + sc_biguint<12>(trunc_ln87_fu_279_p1.read()));
}

void invntt_tomont::thread_add_ln88_1_fu_331_p2() {
    add_ln88_1_fu_331_p2 = (!a_q0.read().is_01() || !a_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(a_q0.read()) + sc_biguint<32>(a_q1.read()));
}

void invntt_tomont::thread_add_ln88_2_fu_307_p2() {
    add_ln88_2_fu_307_p2 = (!zext_ln77_reg_493.read().is_01() || !add_ln88_fu_301_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln77_reg_493.read()) + sc_biguint<12>(add_ln88_fu_301_p2.read()));
}

void invntt_tomont::thread_add_ln88_fu_301_p2() {
    add_ln88_fu_301_p2 = (!zext_ln88_fu_297_p1.read().is_01() || !trunc_ln88_fu_293_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln88_fu_297_p1.read()) + sc_biguint<12>(trunc_ln88_fu_293_p1.read()));
}

void invntt_tomont::thread_add_ln96_fu_417_p2() {
    add_ln96_fu_417_p2 = (!zext_ln96_fu_413_p1.read().is_01() || !zext_ln77_reg_493.read().is_01())? sc_lv<12>(): (sc_biguint<12>(zext_ln96_fu_413_p1.read()) + sc_biguint<12>(zext_ln77_reg_493.read()));
}

void invntt_tomont::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void invntt_tomont::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void invntt_tomont::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void invntt_tomont::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void invntt_tomont::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void invntt_tomont::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void invntt_tomont::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void invntt_tomont::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void invntt_tomont::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void invntt_tomont::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void invntt_tomont::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_401_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void invntt_tomont::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void invntt_tomont::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_401_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void invntt_tomont::thread_empty_55_fu_242_p2() {
    empty_55_fu_242_p2 = (!j_reg_126.read().is_01() || !add_ln86_fu_233_p2.read().is_01())? sc_lv<1>(): (sc_biguint<10>(j_reg_126.read()) > sc_biguint<10>(add_ln86_fu_233_p2.read()));
}

void invntt_tomont::thread_icmp_ln84_fu_201_p2() {
    icmp_ln84_fu_201_p2 = (!tmp_11_fu_191_p4.read().is_01() || !ap_const_lv2_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_11_fu_191_p4.read() == ap_const_lv2_0);
}

void invntt_tomont::thread_icmp_ln86_fu_274_p2() {
    icmp_ln86_fu_274_p2 = (!j_0_reg_138.read().is_01() || !zext_ln86_reg_532.read().is_01())? sc_lv<1>(): (sc_biguint<32>(j_0_reg_138.read()) < sc_biguint<32>(zext_ln86_reg_532.read()));
}

void invntt_tomont::thread_icmp_ln95_fu_401_p2() {
    icmp_ln95_fu_401_p2 = (!j_1_reg_147.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(j_1_reg_147.read() == ap_const_lv9_100);
}

void invntt_tomont::thread_j_3_fu_407_p2() {
    j_3_fu_407_p2 = (!j_1_reg_147.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(j_1_reg_147.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void invntt_tomont::thread_j_4_fu_317_p2() {
    j_4_fu_317_p2 = (!ap_const_lv32_1.is_01() || !j_0_reg_138.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_1) + sc_biguint<32>(j_0_reg_138.read()));
}

void invntt_tomont::thread_k_fu_210_p2() {
    k_fu_210_p2 = (!ap_const_lv32_FFFFFFFF.is_01() || !k_4_fu_58.read().is_01())? sc_lv<32>(): (sc_bigint<32>(ap_const_lv32_FFFFFFFF) + sc_biguint<32>(k_4_fu_58.read()));
}

void invntt_tomont::thread_len_fu_221_p2() {
    len_fu_221_p2 = (!ap_const_lv9_1.is_01())? sc_lv<9>(): len_0_reg_114.read() << (unsigned short)ap_const_lv9_1.to_uint();
}

void invntt_tomont::thread_mul_ln19_2_fu_370_p1() {
    mul_ln19_2_fu_370_p1 = t_11_fu_360_p2.read();
}

void invntt_tomont::thread_mul_ln19_2_fu_370_p2() {
    mul_ln19_2_fu_370_p2 = (!ap_const_lv55_7FFFFFFF801FFF.is_01() || !mul_ln19_2_fu_370_p1.read().is_01())? sc_lv<55>(): sc_bigint<55>(ap_const_lv55_7FFFFFFF801FFF) * sc_bigint<32>(mul_ln19_2_fu_370_p1.read());
}

void invntt_tomont::thread_mul_ln19_fu_455_p1() {
    mul_ln19_fu_455_p1 = t_9_fu_445_p2.read();
}

void invntt_tomont::thread_mul_ln19_fu_455_p2() {
    mul_ln19_fu_455_p2 = (!ap_const_lv55_7FFFFFFF801FFF.is_01() || !mul_ln19_fu_455_p1.read().is_01())? sc_lv<55>(): sc_bigint<55>(ap_const_lv55_7FFFFFFF801FFF) * sc_bigint<32>(mul_ln19_fu_455_p1.read());
}

void invntt_tomont::thread_mul_ln90_fu_347_p0() {
    mul_ln90_fu_347_p0 =  (sc_lv<23>) (sext_ln86_reg_542.read());
}

void invntt_tomont::thread_mul_ln90_fu_347_p1() {
    mul_ln90_fu_347_p1 = sub_ln89_fu_338_p2.read();
}

void invntt_tomont::thread_mul_ln90_fu_347_p2() {
    mul_ln90_fu_347_p2 = (!mul_ln90_fu_347_p0.read().is_01() || !mul_ln90_fu_347_p1.read().is_01())? sc_lv<54>(): sc_bigint<23>(mul_ln90_fu_347_p0.read()) * sc_bigint<32>(mul_ln90_fu_347_p1.read());
}

void invntt_tomont::thread_mul_ln96_fu_431_p1() {
    mul_ln96_fu_431_p1 = sext_ln96_fu_427_p0.read();
}

void invntt_tomont::thread_mul_ln96_fu_431_p2() {
    mul_ln96_fu_431_p2 = (!ap_const_lv49_A3FA.is_01() || !mul_ln96_fu_431_p1.read().is_01())? sc_lv<49>(): sc_biguint<49>(ap_const_lv49_A3FA) * sc_bigint<32>(mul_ln96_fu_431_p1.read());
}

void invntt_tomont::thread_sext_ln19_12_fu_376_p1() {
    sext_ln19_12_fu_376_p1 = esl_sext<56,55>(mul_ln19_2_fu_370_p2.read());
}

void invntt_tomont::thread_sext_ln19_9_fu_461_p1() {
    sext_ln19_9_fu_461_p1 = esl_sext<56,55>(mul_ln19_fu_455_p2.read());
}

void invntt_tomont::thread_sext_ln86_fu_270_p1() {
    sext_ln86_fu_270_p1 = esl_sext<54,23>(zeta_fu_227_p2.read());
}

void invntt_tomont::thread_sext_ln90_1_fu_352_p1() {
    sext_ln90_1_fu_352_p1 = esl_sext<56,54>(mul_ln90_fu_347_p2.read());
}

void invntt_tomont::thread_sext_ln96_1_fu_437_p1() {
    sext_ln96_1_fu_437_p1 = esl_sext<56,49>(mul_ln96_fu_431_p2.read());
}

void invntt_tomont::thread_sext_ln96_fu_427_p0() {
    sext_ln96_fu_427_p0 = a_q1.read();
}

void invntt_tomont::thread_start_fu_258_p3() {
    start_fu_258_p3 = (!empty_55_fu_242_p2.read()[0].is_01())? sc_lv<9>(): ((empty_55_fu_242_p2.read()[0].to_bool())? trunc_ln84_fu_248_p1.read(): add_ln84_1_fu_252_p2.read());
}

void invntt_tomont::thread_sub_ln89_fu_338_p2() {
    sub_ln89_fu_338_p2 = (!t_reg_571.read().is_01() || !a_q1.read().is_01())? sc_lv<32>(): (sc_biguint<32>(t_reg_571.read()) - sc_biguint<32>(a_q1.read()));
}

void invntt_tomont::thread_t_10_fu_481_p1() {
    t_10_fu_481_p1 = esl_sext<32,24>(trunc_ln_fu_471_p4.read());
}

void invntt_tomont::thread_t_11_fu_360_p2() {
    t_11_fu_360_p2 = (!ap_const_lv32_3802001.is_01() || !trunc_ln18_2_fu_356_p1.read().is_01())? sc_lv<32>(): sc_biguint<32>(ap_const_lv32_3802001) * sc_bigint<32>(trunc_ln18_2_fu_356_p1.read());
}

void invntt_tomont::thread_t_12_fu_396_p1() {
    t_12_fu_396_p1 = esl_sext<32,24>(trunc_ln19_1_fu_386_p4.read());
}

void invntt_tomont::thread_t_9_fu_445_p2() {
    t_9_fu_445_p2 = (!ap_const_lv32_3802001.is_01() || !trunc_ln18_fu_441_p1.read().is_01())? sc_lv<32>(): sc_biguint<32>(ap_const_lv32_3802001) * sc_bigint<32>(trunc_ln18_fu_441_p1.read());
}

void invntt_tomont::thread_tmp_10_fu_179_p3() {
    tmp_10_fu_179_p3 = len_0_reg_114.read().range(8, 8);
}

void invntt_tomont::thread_tmp_11_fu_191_p4() {
    tmp_11_fu_191_p4 = j_reg_126.read().range(9, 8);
}

void invntt_tomont::thread_tmp_fu_158_p3() {
    tmp_fu_158_p3 = esl_concat<3,8>(a_offset.read(), ap_const_lv8_0);
}

void invntt_tomont::thread_trunc_ln18_2_fu_356_p1() {
    trunc_ln18_2_fu_356_p1 = mul_ln90_fu_347_p2.read().range(32-1, 0);
}

void invntt_tomont::thread_trunc_ln18_fu_441_p1() {
    trunc_ln18_fu_441_p1 = mul_ln96_fu_431_p2.read().range(32-1, 0);
}

void invntt_tomont::thread_trunc_ln19_1_fu_386_p4() {
    trunc_ln19_1_fu_386_p4 = add_ln19_2_fu_380_p2.read().range(55, 32);
}

void invntt_tomont::thread_trunc_ln84_fu_248_p1() {
    trunc_ln84_fu_248_p1 = j_reg_126.read().range(9-1, 0);
}

void invntt_tomont::thread_trunc_ln87_fu_279_p1() {
    trunc_ln87_fu_279_p1 = j_0_reg_138.read().range(12-1, 0);
}

void invntt_tomont::thread_trunc_ln88_fu_293_p1() {
    trunc_ln88_fu_293_p1 = j_0_reg_138.read().range(12-1, 0);
}

void invntt_tomont::thread_trunc_ln_fu_471_p4() {
    trunc_ln_fu_471_p4 = add_ln19_fu_465_p2.read().range(55, 32);
}

void invntt_tomont::thread_zeta_fu_227_p2() {
    zeta_fu_227_p2 = (!ap_const_lv23_0.is_01() || !zetas_q0.read().is_01())? sc_lv<23>(): (sc_biguint<23>(ap_const_lv23_0) - sc_biguint<23>(zetas_q0.read()));
}

void invntt_tomont::thread_zetas_address0() {
    zetas_address0 =  (sc_lv<8>) (zext_ln85_fu_216_p1.read());
}

void invntt_tomont::thread_zetas_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        zetas_ce0 = ap_const_logic_1;
    } else {
        zetas_ce0 = ap_const_logic_0;
    }
}

void invntt_tomont::thread_zext_ln77_fu_166_p1() {
    zext_ln77_fu_166_p1 = esl_zext<12,11>(tmp_fu_158_p3.read());
}

void invntt_tomont::thread_zext_ln83_fu_175_p1() {
    zext_ln83_fu_175_p1 = esl_zext<10,9>(len_0_reg_114.read());
}

void invntt_tomont::thread_zext_ln84_1_fu_266_p1() {
    zext_ln84_1_fu_266_p1 = esl_zext<10,9>(start_fu_258_p3.read());
}

void invntt_tomont::thread_zext_ln84_fu_187_p1() {
    zext_ln84_fu_187_p1 = esl_zext<32,10>(j_reg_126.read());
}

void invntt_tomont::thread_zext_ln85_fu_216_p1() {
    zext_ln85_fu_216_p1 = esl_zext<64,32>(k_fu_210_p2.read());
}

void invntt_tomont::thread_zext_ln86_fu_238_p1() {
    zext_ln86_fu_238_p1 = esl_zext<32,10>(add_ln86_fu_233_p2.read());
}

void invntt_tomont::thread_zext_ln87_fu_288_p1() {
    zext_ln87_fu_288_p1 = esl_zext<64,12>(add_ln87_fu_283_p2.read());
}

void invntt_tomont::thread_zext_ln88_3_fu_312_p1() {
    zext_ln88_3_fu_312_p1 = esl_zext<64,12>(add_ln88_2_fu_307_p2.read());
}

void invntt_tomont::thread_zext_ln88_fu_297_p1() {
    zext_ln88_fu_297_p1 = esl_zext<12,9>(len_0_reg_114.read());
}

void invntt_tomont::thread_zext_ln96_1_fu_422_p1() {
    zext_ln96_1_fu_422_p1 = esl_zext<64,12>(add_ln96_fu_417_p2.read());
}

void invntt_tomont::thread_zext_ln96_fu_413_p1() {
    zext_ln96_fu_413_p1 = esl_zext<12,9>(j_1_reg_147.read());
}

void invntt_tomont::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_10_fu_179_p3.read()))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln84_fu_201_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln86_fu_274_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln95_fu_401_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

