// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "load64_3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic load64_3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic load64_3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> load64_3::ap_ST_fsm_state1 = "1";
const sc_lv<2> load64_3::ap_ST_fsm_state2 = "10";
const sc_lv<32> load64_3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> load64_3::ap_const_lv32_1 = "1";
const sc_lv<1> load64_3::ap_const_lv1_0 = "0";
const sc_lv<4> load64_3::ap_const_lv4_0 = "0000";
const sc_lv<64> load64_3::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<4> load64_3::ap_const_lv4_8 = "1000";
const sc_lv<4> load64_3::ap_const_lv4_1 = "1";
const sc_lv<3> load64_3::ap_const_lv3_0 = "000";
const sc_lv<1> load64_3::ap_const_lv1_1 = "1";
const bool load64_3::ap_const_boolean_1 = true;

load64_3::load64_3(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln30_fu_70_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln30_fu_70_p2 );

    SC_METHOD(thread_ap_return);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln30_fu_70_p2 );
    sensitive << ( r_0_reg_55 );
    sensitive << ( ap_return_preg );

    SC_METHOD(thread_i_fu_76_p2);
    sensitive << ( i_0_reg_44 );

    SC_METHOD(thread_icmp_ln30_fu_70_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_44 );

    SC_METHOD(thread_r_fu_123_p2);
    sensitive << ( r_0_reg_55 );
    sensitive << ( shl_ln31_fu_117_p2 );

    SC_METHOD(thread_select_ln31_fu_91_p3);
    sensitive << ( x_0_read );
    sensitive << ( x_1_read );
    sensitive << ( xor_ln31_fu_86_p2 );

    SC_METHOD(thread_shl_ln31_fu_117_p2);
    sensitive << ( zext_ln31_fu_97_p1 );
    sensitive << ( zext_ln31_1_fu_113_p1 );

    SC_METHOD(thread_shl_ln_fu_105_p3);
    sensitive << ( trunc_ln31_2_fu_101_p1 );

    SC_METHOD(thread_trunc_ln31_1_fu_82_p1);
    sensitive << ( i_0_reg_44 );

    SC_METHOD(thread_trunc_ln31_2_fu_101_p1);
    sensitive << ( i_0_reg_44 );

    SC_METHOD(thread_trunc_ln31_fu_66_p1);
    sensitive << ( x_offset );

    SC_METHOD(thread_xor_ln31_fu_86_p2);
    sensitive << ( trunc_ln31_reg_139 );
    sensitive << ( trunc_ln31_1_fu_82_p1 );

    SC_METHOD(thread_zext_ln31_1_fu_113_p1);
    sensitive << ( shl_ln_fu_105_p3 );

    SC_METHOD(thread_zext_ln31_fu_97_p1);
    sensitive << ( select_ln31_fu_91_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln30_fu_70_p2 );

    ap_CS_fsm = "01";
    ap_return_preg = "0000000000000000000000000000000000000000000000000000000000000000";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "load64_3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, x_0_read, "(port)x_0_read");
    sc_trace(mVcdFile, x_1_read, "(port)x_1_read");
    sc_trace(mVcdFile, x_offset, "(port)x_offset");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, trunc_ln31_fu_66_p1, "trunc_ln31_fu_66_p1");
    sc_trace(mVcdFile, trunc_ln31_reg_139, "trunc_ln31_reg_139");
    sc_trace(mVcdFile, i_fu_76_p2, "i_fu_76_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, r_fu_123_p2, "r_fu_123_p2");
    sc_trace(mVcdFile, icmp_ln30_fu_70_p2, "icmp_ln30_fu_70_p2");
    sc_trace(mVcdFile, i_0_reg_44, "i_0_reg_44");
    sc_trace(mVcdFile, r_0_reg_55, "r_0_reg_55");
    sc_trace(mVcdFile, trunc_ln31_1_fu_82_p1, "trunc_ln31_1_fu_82_p1");
    sc_trace(mVcdFile, xor_ln31_fu_86_p2, "xor_ln31_fu_86_p2");
    sc_trace(mVcdFile, select_ln31_fu_91_p3, "select_ln31_fu_91_p3");
    sc_trace(mVcdFile, trunc_ln31_2_fu_101_p1, "trunc_ln31_2_fu_101_p1");
    sc_trace(mVcdFile, shl_ln_fu_105_p3, "shl_ln_fu_105_p3");
    sc_trace(mVcdFile, zext_ln31_fu_97_p1, "zext_ln31_fu_97_p1");
    sc_trace(mVcdFile, zext_ln31_1_fu_113_p1, "zext_ln31_1_fu_113_p1");
    sc_trace(mVcdFile, shl_ln31_fu_117_p2, "shl_ln31_fu_117_p2");
    sc_trace(mVcdFile, ap_return_preg, "ap_return_preg");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

load64_3::~load64_3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void load64_3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_return_preg = ap_const_lv64_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
             esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_1))) {
            ap_return_preg = r_0_reg_55.read();
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_0))) {
        i_0_reg_44 = i_fu_76_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_44 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_0))) {
        r_0_reg_55 = r_fu_123_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        r_0_reg_55 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        trunc_ln31_reg_139 = trunc_ln31_fu_66_p1.read();
    }
}

void load64_3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void load64_3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void load64_3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void load64_3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void load64_3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void load64_3::thread_ap_return() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_1))) {
        ap_return = r_0_reg_55.read();
    } else {
        ap_return = ap_return_preg.read();
    }
}

void load64_3::thread_i_fu_76_p2() {
    i_fu_76_p2 = (!i_0_reg_44.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_44.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void load64_3::thread_icmp_ln30_fu_70_p2() {
    icmp_ln30_fu_70_p2 = (!i_0_reg_44.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_44.read() == ap_const_lv4_8);
}

void load64_3::thread_r_fu_123_p2() {
    r_fu_123_p2 = (shl_ln31_fu_117_p2.read() | r_0_reg_55.read());
}

void load64_3::thread_select_ln31_fu_91_p3() {
    select_ln31_fu_91_p3 = (!xor_ln31_fu_86_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln31_fu_86_p2.read()[0].to_bool())? x_1_read.read(): x_0_read.read());
}

void load64_3::thread_shl_ln31_fu_117_p2() {
    shl_ln31_fu_117_p2 = (!zext_ln31_1_fu_113_p1.read().is_01())? sc_lv<64>(): zext_ln31_fu_97_p1.read() << (unsigned short)zext_ln31_1_fu_113_p1.read().to_uint();
}

void load64_3::thread_shl_ln_fu_105_p3() {
    shl_ln_fu_105_p3 = esl_concat<3,3>(trunc_ln31_2_fu_101_p1.read(), ap_const_lv3_0);
}

void load64_3::thread_trunc_ln31_1_fu_82_p1() {
    trunc_ln31_1_fu_82_p1 = i_0_reg_44.read().range(1-1, 0);
}

void load64_3::thread_trunc_ln31_2_fu_101_p1() {
    trunc_ln31_2_fu_101_p1 = i_0_reg_44.read().range(3-1, 0);
}

void load64_3::thread_trunc_ln31_fu_66_p1() {
    trunc_ln31_fu_66_p1 = x_offset.read().range(1-1, 0);
}

void load64_3::thread_xor_ln31_fu_86_p2() {
    xor_ln31_fu_86_p2 = (trunc_ln31_1_fu_82_p1.read() ^ trunc_ln31_reg_139.read());
}

void load64_3::thread_zext_ln31_1_fu_113_p1() {
    zext_ln31_1_fu_113_p1 = esl_zext<64,6>(shl_ln_fu_105_p3.read());
}

void load64_3::thread_zext_ln31_fu_97_p1() {
    zext_ln31_fu_97_p1 = esl_zext<64,8>(select_ln31_fu_91_p3.read());
}

void load64_3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln30_fu_70_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        default : 
            ap_NS_fsm = "XX";
            break;
    }
}

}

