// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pqcrystals_dilithium_9.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pqcrystals_dilithium_9::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic pqcrystals_dilithium_9::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state1 = "1";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state2 = "10";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state3 = "100";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state4 = "1000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state5 = "10000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state6 = "100000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> pqcrystals_dilithium_9::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_1 = "1";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_2 = "10";
const sc_lv<1> pqcrystals_dilithium_9::ap_const_lv1_0 = "0";
const sc_lv<1> pqcrystals_dilithium_9::ap_const_lv1_1 = "1";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_3 = "11";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_4 = "100";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_5 = "101";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_7 = "111";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_A = "1010";
const sc_lv<5> pqcrystals_dilithium_9::ap_const_lv5_0 = "00000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_6 = "110";
const sc_lv<3> pqcrystals_dilithium_9::ap_const_lv3_0 = "000";
const sc_lv<9> pqcrystals_dilithium_9::ap_const_lv9_88 = "10001000";
const sc_lv<7> pqcrystals_dilithium_9::ap_const_lv7_30 = "110000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_C = "1100";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_D = "1101";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_E = "1110";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_F = "1111";
const sc_lv<64> pqcrystals_dilithium_9::ap_const_lv64_10 = "10000";
const sc_lv<64> pqcrystals_dilithium_9::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_8 = "1000";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_9 = "1001";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_B = "1011";
const sc_lv<5> pqcrystals_dilithium_9::ap_const_lv5_19 = "11001";
const sc_lv<5> pqcrystals_dilithium_9::ap_const_lv5_1 = "1";
const sc_lv<3> pqcrystals_dilithium_9::ap_const_lv3_6 = "110";
const sc_lv<3> pqcrystals_dilithium_9::ap_const_lv3_1 = "1";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A0 = "10100000";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A1 = "10100001";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A2 = "10100010";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A3 = "10100011";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A4 = "10100100";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A5 = "10100101";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A6 = "10100110";
const sc_lv<8> pqcrystals_dilithium_9::ap_const_lv8_A7 = "10100111";
const sc_lv<32> pqcrystals_dilithium_9::ap_const_lv32_1F = "11111";
const sc_lv<64> pqcrystals_dilithium_9::ap_const_lv64_1F = "11111";
const sc_lv<64> pqcrystals_dilithium_9::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const bool pqcrystals_dilithium_9::ap_const_boolean_1 = true;

pqcrystals_dilithium_9::pqcrystals_dilithium_9(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_U = new pqcrystals_dilithfYi("buf_U");
    buf_U->clk(ap_clk);
    buf_U->reset(ap_rst);
    buf_U->address0(buf_address0);
    buf_U->ce0(buf_ce0);
    buf_U->we0(buf_we0);
    buf_U->d0(grp_keccak_squeezeblocks_1_fu_241_out_r_d0);
    buf_U->q0(buf_q0);
    buf_U->address1(grp_pqcrystals_dilithium_2_fu_247_a_address1);
    buf_U->ce1(buf_ce1);
    buf_U->q1(buf_q1);
    state_s_U = new pqcrystals_dilithcud("state_s_U");
    state_s_U->clk(ap_clk);
    state_s_U->reset(ap_rst);
    state_s_U->address0(state_s_address0);
    state_s_U->ce0(state_s_ce0);
    state_s_U->we0(state_s_we0);
    state_s_U->d0(state_s_d0);
    state_s_U->q0(state_s_q0);
    state_s_U->address1(state_s_address1);
    state_s_U->ce1(state_s_ce1);
    state_s_U->we1(state_s_we1);
    state_s_U->d1(state_s_d1);
    state_s_U->q1(state_s_q1);
    grp_keccak_absorb_fu_230 = new keccak_absorb("grp_keccak_absorb_fu_230");
    grp_keccak_absorb_fu_230->ap_clk(ap_clk);
    grp_keccak_absorb_fu_230->ap_rst(ap_rst);
    grp_keccak_absorb_fu_230->ap_start(grp_keccak_absorb_fu_230_ap_start);
    grp_keccak_absorb_fu_230->ap_done(grp_keccak_absorb_fu_230_ap_done);
    grp_keccak_absorb_fu_230->ap_idle(grp_keccak_absorb_fu_230_ap_idle);
    grp_keccak_absorb_fu_230->ap_ready(grp_keccak_absorb_fu_230_ap_ready);
    grp_keccak_absorb_fu_230->s_address0(grp_keccak_absorb_fu_230_s_address0);
    grp_keccak_absorb_fu_230->s_ce0(grp_keccak_absorb_fu_230_s_ce0);
    grp_keccak_absorb_fu_230->s_we0(grp_keccak_absorb_fu_230_s_we0);
    grp_keccak_absorb_fu_230->s_d0(grp_keccak_absorb_fu_230_s_d0);
    grp_keccak_absorb_fu_230->s_q0(state_s_q0);
    grp_keccak_absorb_fu_230->s_address1(grp_keccak_absorb_fu_230_s_address1);
    grp_keccak_absorb_fu_230->s_ce1(grp_keccak_absorb_fu_230_s_ce1);
    grp_keccak_absorb_fu_230->s_we1(grp_keccak_absorb_fu_230_s_we1);
    grp_keccak_absorb_fu_230->s_d1(grp_keccak_absorb_fu_230_s_d1);
    grp_keccak_absorb_fu_230->s_q1(state_s_q1);
    grp_keccak_absorb_fu_230->r(ap_var_for_const0);
    grp_keccak_absorb_fu_230->pos_r(ap_var_for_const1);
    grp_keccak_absorb_fu_230->m_0_read(t_0_reg_476);
    grp_keccak_absorb_fu_230->m_1_read(t_1_reg_481);
    grp_keccak_absorb_fu_230->ap_return(grp_keccak_absorb_fu_230_ap_return);
    grp_keccak_squeezeblocks_1_fu_241 = new keccak_squeezeblocks_1("grp_keccak_squeezeblocks_1_fu_241");
    grp_keccak_squeezeblocks_1_fu_241->ap_clk(ap_clk);
    grp_keccak_squeezeblocks_1_fu_241->ap_rst(ap_rst);
    grp_keccak_squeezeblocks_1_fu_241->ap_start(grp_keccak_squeezeblocks_1_fu_241_ap_start);
    grp_keccak_squeezeblocks_1_fu_241->ap_done(grp_keccak_squeezeblocks_1_fu_241_ap_done);
    grp_keccak_squeezeblocks_1_fu_241->ap_idle(grp_keccak_squeezeblocks_1_fu_241_ap_idle);
    grp_keccak_squeezeblocks_1_fu_241->ap_ready(grp_keccak_squeezeblocks_1_fu_241_ap_ready);
    grp_keccak_squeezeblocks_1_fu_241->out_r_address0(grp_keccak_squeezeblocks_1_fu_241_out_r_address0);
    grp_keccak_squeezeblocks_1_fu_241->out_r_ce0(grp_keccak_squeezeblocks_1_fu_241_out_r_ce0);
    grp_keccak_squeezeblocks_1_fu_241->out_r_we0(grp_keccak_squeezeblocks_1_fu_241_out_r_we0);
    grp_keccak_squeezeblocks_1_fu_241->out_r_d0(grp_keccak_squeezeblocks_1_fu_241_out_r_d0);
    grp_keccak_squeezeblocks_1_fu_241->s_address0(grp_keccak_squeezeblocks_1_fu_241_s_address0);
    grp_keccak_squeezeblocks_1_fu_241->s_ce0(grp_keccak_squeezeblocks_1_fu_241_s_ce0);
    grp_keccak_squeezeblocks_1_fu_241->s_we0(grp_keccak_squeezeblocks_1_fu_241_s_we0);
    grp_keccak_squeezeblocks_1_fu_241->s_d0(grp_keccak_squeezeblocks_1_fu_241_s_d0);
    grp_keccak_squeezeblocks_1_fu_241->s_q0(state_s_q0);
    grp_keccak_squeezeblocks_1_fu_241->s_address1(grp_keccak_squeezeblocks_1_fu_241_s_address1);
    grp_keccak_squeezeblocks_1_fu_241->s_ce1(grp_keccak_squeezeblocks_1_fu_241_s_ce1);
    grp_keccak_squeezeblocks_1_fu_241->s_we1(grp_keccak_squeezeblocks_1_fu_241_s_we1);
    grp_keccak_squeezeblocks_1_fu_241->s_d1(grp_keccak_squeezeblocks_1_fu_241_s_d1);
    grp_keccak_squeezeblocks_1_fu_241->s_q1(state_s_q1);
    grp_pqcrystals_dilithium_2_fu_247 = new pqcrystals_dilithium_2("grp_pqcrystals_dilithium_2_fu_247");
    grp_pqcrystals_dilithium_2_fu_247->ap_clk(ap_clk);
    grp_pqcrystals_dilithium_2_fu_247->ap_rst(ap_rst);
    grp_pqcrystals_dilithium_2_fu_247->ap_start(grp_pqcrystals_dilithium_2_fu_247_ap_start);
    grp_pqcrystals_dilithium_2_fu_247->ap_done(grp_pqcrystals_dilithium_2_fu_247_ap_done);
    grp_pqcrystals_dilithium_2_fu_247->ap_idle(grp_pqcrystals_dilithium_2_fu_247_ap_idle);
    grp_pqcrystals_dilithium_2_fu_247->ap_ready(grp_pqcrystals_dilithium_2_fu_247_ap_ready);
    grp_pqcrystals_dilithium_2_fu_247->r_coeffs_address0(grp_pqcrystals_dilithium_2_fu_247_r_coeffs_address0);
    grp_pqcrystals_dilithium_2_fu_247->r_coeffs_ce0(grp_pqcrystals_dilithium_2_fu_247_r_coeffs_ce0);
    grp_pqcrystals_dilithium_2_fu_247->r_coeffs_we0(grp_pqcrystals_dilithium_2_fu_247_r_coeffs_we0);
    grp_pqcrystals_dilithium_2_fu_247->r_coeffs_d0(grp_pqcrystals_dilithium_2_fu_247_r_coeffs_d0);
    grp_pqcrystals_dilithium_2_fu_247->r_coeffs_offset(trunc_ln503_reg_527);
    grp_pqcrystals_dilithium_2_fu_247->a_address0(grp_pqcrystals_dilithium_2_fu_247_a_address0);
    grp_pqcrystals_dilithium_2_fu_247->a_ce0(grp_pqcrystals_dilithium_2_fu_247_a_ce0);
    grp_pqcrystals_dilithium_2_fu_247->a_q0(buf_q0);
    grp_pqcrystals_dilithium_2_fu_247->a_address1(grp_pqcrystals_dilithium_2_fu_247_a_address1);
    grp_pqcrystals_dilithium_2_fu_247->a_ce1(grp_pqcrystals_dilithium_2_fu_247_a_ce1);
    grp_pqcrystals_dilithium_2_fu_247->a_q1(buf_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_coeffs_address0);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_r_coeffs_address0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_a_coeffs_ce0);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_r_coeffs_ce0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_a_coeffs_d0);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_r_coeffs_d0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_a_coeffs_we0);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_r_coeffs_we0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_add_ln32_1_fu_340_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_2_fu_350_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_3_fu_360_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_4_fu_370_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_5_fu_380_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_6_fu_390_p2);
    sensitive << ( zext_ln421_reg_502 );

    SC_METHOD(thread_add_ln32_fu_326_p2);
    sensitive << ( zext_ln421_fu_311_p1 );

    SC_METHOD(thread_add_ln420_fu_297_p2);
    sensitive << ( i_3_i_reg_219 );

    SC_METHOD(thread_add_ln421_fu_315_p2);
    sensitive << ( zext_ln421_fu_311_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_ap_done );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_ap_done );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_buf_address0);
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_out_r_address0 );
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_a_address0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_buf_ce0);
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_out_r_ce0 );
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_a_ce0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_buf_ce1);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_a_ce1 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_buf_we0);
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_out_r_we0 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_grp_keccak_absorb_fu_230_ap_start);
    sensitive << ( grp_keccak_absorb_fu_230_ap_start_reg );

    SC_METHOD(thread_grp_keccak_squeezeblocks_1_fu_241_ap_start);
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_ap_start_reg );

    SC_METHOD(thread_grp_pqcrystals_dilithium_2_fu_247_ap_start);
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_ap_start_reg );

    SC_METHOD(thread_i_1_fu_275_p2);
    sensitive << ( i_0_i_i_i_reg_208 );

    SC_METHOD(thread_i_fu_421_p4);
    sensitive << ( grp_keccak_absorb_fu_230_ap_return );

    SC_METHOD(thread_icmp_ln364_fu_269_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_i_i_reg_208 );

    SC_METHOD(thread_icmp_ln420_fu_291_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_3_i_reg_219 );

    SC_METHOD(thread_r_7_i1_i_fu_400_p9);
    sensitive << ( seed_q0 );
    sensitive << ( seed_q1 );
    sensitive << ( seed_load_reg_532 );
    sensitive << ( seed_load_1_reg_537 );
    sensitive << ( seed_load_2_reg_552 );
    sensitive << ( seed_load_3_reg_557 );
    sensitive << ( seed_load_4_reg_572 );
    sensitive << ( seed_load_5_reg_577 );

    SC_METHOD(thread_seed_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln421_1_fu_321_p1 );
    sensitive << ( zext_ln32_1_fu_345_p1 );
    sensitive << ( zext_ln32_3_fu_365_p1 );
    sensitive << ( zext_ln32_5_fu_385_p1 );

    SC_METHOD(thread_seed_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln32_fu_332_p1 );
    sensitive << ( zext_ln32_2_fu_355_p1 );
    sensitive << ( zext_ln32_4_fu_375_p1 );
    sensitive << ( zext_ln32_6_fu_395_p1 );

    SC_METHOD(thread_seed_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_seed_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_shl_ln1_fu_303_p3);
    sensitive << ( i_3_i_reg_219 );

    SC_METHOD(thread_shl_ln454_fu_451_p2);
    sensitive << ( zext_ln454_fu_447_p1 );

    SC_METHOD(thread_shl_ln_fu_439_p3);
    sensitive << ( trunc_ln454_fu_436_p1 );

    SC_METHOD(thread_state_s_addr_2_reg_602);
    sensitive << ( ap_CS_fsm_state11 );

    SC_METHOD(thread_state_s_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( state_s_addr_3_reg_522 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( state_s_addr_1_reg_597 );
    sensitive << ( state_s_addr_2_reg_602 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_keccak_absorb_fu_230_s_address0 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_address0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( zext_ln365_fu_281_p1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_state_s_address1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_address1 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_address1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_state_s_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( grp_keccak_absorb_fu_230_s_ce0 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_ce0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_state_s_ce1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_ce1 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_ce1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_state_s_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_d0 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_d0 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( xor_ln421_fu_414_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( xor_ln454_fu_457_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( xor_ln455_fu_464_p2 );

    SC_METHOD(thread_state_s_d1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_d1 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_d1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_state_s_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_we0 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_we0 );
    sensitive << ( icmp_ln364_fu_269_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_state_s_we1);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_s_we1 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_s_we1 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_t_0_fu_255_p1);
    sensitive << ( nonce );

    SC_METHOD(thread_trunc_ln454_fu_436_p1);
    sensitive << ( state_pos_write_assi_reg_592 );

    SC_METHOD(thread_trunc_ln503_fu_337_p1);
    sensitive << ( a_coeffs_offset );

    SC_METHOD(thread_xor_ln421_fu_414_p2);
    sensitive << ( state_s_q0 );
    sensitive << ( r_7_i1_i_fu_400_p9 );

    SC_METHOD(thread_xor_ln454_fu_457_p2);
    sensitive << ( state_s_q0 );
    sensitive << ( shl_ln454_fu_451_p2 );

    SC_METHOD(thread_xor_ln455_fu_464_p2);
    sensitive << ( state_s_q0 );

    SC_METHOD(thread_zext_ln32_1_fu_345_p1);
    sensitive << ( add_ln32_1_fu_340_p2 );

    SC_METHOD(thread_zext_ln32_2_fu_355_p1);
    sensitive << ( add_ln32_2_fu_350_p2 );

    SC_METHOD(thread_zext_ln32_3_fu_365_p1);
    sensitive << ( add_ln32_3_fu_360_p2 );

    SC_METHOD(thread_zext_ln32_4_fu_375_p1);
    sensitive << ( add_ln32_4_fu_370_p2 );

    SC_METHOD(thread_zext_ln32_5_fu_385_p1);
    sensitive << ( add_ln32_5_fu_380_p2 );

    SC_METHOD(thread_zext_ln32_6_fu_395_p1);
    sensitive << ( add_ln32_6_fu_390_p2 );

    SC_METHOD(thread_zext_ln32_fu_332_p1);
    sensitive << ( add_ln32_fu_326_p2 );

    SC_METHOD(thread_zext_ln365_fu_281_p1);
    sensitive << ( i_0_i_i_i_reg_208 );

    SC_METHOD(thread_zext_ln420_fu_286_p1);
    sensitive << ( i_3_i_reg_219 );

    SC_METHOD(thread_zext_ln421_1_fu_321_p1);
    sensitive << ( add_ln421_fu_315_p2 );

    SC_METHOD(thread_zext_ln421_fu_311_p1);
    sensitive << ( shl_ln1_fu_303_p3 );

    SC_METHOD(thread_zext_ln454_1_fu_431_p1);
    sensitive << ( i_fu_421_p4 );

    SC_METHOD(thread_zext_ln454_fu_447_p1);
    sensitive << ( shl_ln_fu_439_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln420_fu_291_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_keccak_absorb_fu_230_ap_done );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_241_ap_done );
    sensitive << ( grp_pqcrystals_dilithium_2_fu_247_ap_done );
    sensitive << ( icmp_ln364_fu_269_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000001";
    grp_keccak_absorb_fu_230_ap_start_reg = SC_LOGIC_0;
    grp_keccak_squeezeblocks_1_fu_241_ap_start_reg = SC_LOGIC_0;
    grp_pqcrystals_dilithium_2_fu_247_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pqcrystals_dilithium_9_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_coeffs_address0, "(port)a_coeffs_address0");
    sc_trace(mVcdFile, a_coeffs_ce0, "(port)a_coeffs_ce0");
    sc_trace(mVcdFile, a_coeffs_we0, "(port)a_coeffs_we0");
    sc_trace(mVcdFile, a_coeffs_d0, "(port)a_coeffs_d0");
    sc_trace(mVcdFile, a_coeffs_offset, "(port)a_coeffs_offset");
    sc_trace(mVcdFile, seed_address0, "(port)seed_address0");
    sc_trace(mVcdFile, seed_ce0, "(port)seed_ce0");
    sc_trace(mVcdFile, seed_q0, "(port)seed_q0");
    sc_trace(mVcdFile, seed_address1, "(port)seed_address1");
    sc_trace(mVcdFile, seed_ce1, "(port)seed_ce1");
    sc_trace(mVcdFile, seed_q1, "(port)seed_q1");
    sc_trace(mVcdFile, nonce, "(port)nonce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, t_0_fu_255_p1, "t_0_fu_255_p1");
    sc_trace(mVcdFile, t_0_reg_476, "t_0_reg_476");
    sc_trace(mVcdFile, t_1_reg_481, "t_1_reg_481");
    sc_trace(mVcdFile, i_1_fu_275_p2, "i_1_fu_275_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, add_ln420_fu_297_p2, "add_ln420_fu_297_p2");
    sc_trace(mVcdFile, add_ln420_reg_497, "add_ln420_reg_497");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, zext_ln421_fu_311_p1, "zext_ln421_fu_311_p1");
    sc_trace(mVcdFile, zext_ln421_reg_502, "zext_ln421_reg_502");
    sc_trace(mVcdFile, icmp_ln420_fu_291_p2, "icmp_ln420_fu_291_p2");
    sc_trace(mVcdFile, state_s_addr_3_reg_522, "state_s_addr_3_reg_522");
    sc_trace(mVcdFile, trunc_ln503_fu_337_p1, "trunc_ln503_fu_337_p1");
    sc_trace(mVcdFile, trunc_ln503_reg_527, "trunc_ln503_reg_527");
    sc_trace(mVcdFile, seed_load_reg_532, "seed_load_reg_532");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, seed_load_1_reg_537, "seed_load_1_reg_537");
    sc_trace(mVcdFile, seed_load_2_reg_552, "seed_load_2_reg_552");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, seed_load_3_reg_557, "seed_load_3_reg_557");
    sc_trace(mVcdFile, seed_load_4_reg_572, "seed_load_4_reg_572");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, seed_load_5_reg_577, "seed_load_5_reg_577");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_return, "grp_keccak_absorb_fu_230_ap_return");
    sc_trace(mVcdFile, state_pos_write_assi_reg_592, "state_pos_write_assi_reg_592");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_ready, "grp_keccak_absorb_fu_230_ap_ready");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_done, "grp_keccak_absorb_fu_230_ap_done");
    sc_trace(mVcdFile, state_s_addr_1_reg_597, "state_s_addr_1_reg_597");
    sc_trace(mVcdFile, state_s_addr_2_reg_602, "state_s_addr_2_reg_602");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, buf_address0, "buf_address0");
    sc_trace(mVcdFile, buf_ce0, "buf_ce0");
    sc_trace(mVcdFile, buf_we0, "buf_we0");
    sc_trace(mVcdFile, buf_q0, "buf_q0");
    sc_trace(mVcdFile, buf_ce1, "buf_ce1");
    sc_trace(mVcdFile, buf_q1, "buf_q1");
    sc_trace(mVcdFile, state_s_address0, "state_s_address0");
    sc_trace(mVcdFile, state_s_ce0, "state_s_ce0");
    sc_trace(mVcdFile, state_s_we0, "state_s_we0");
    sc_trace(mVcdFile, state_s_d0, "state_s_d0");
    sc_trace(mVcdFile, state_s_q0, "state_s_q0");
    sc_trace(mVcdFile, state_s_address1, "state_s_address1");
    sc_trace(mVcdFile, state_s_ce1, "state_s_ce1");
    sc_trace(mVcdFile, state_s_we1, "state_s_we1");
    sc_trace(mVcdFile, state_s_d1, "state_s_d1");
    sc_trace(mVcdFile, state_s_q1, "state_s_q1");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_start, "grp_keccak_absorb_fu_230_ap_start");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_idle, "grp_keccak_absorb_fu_230_ap_idle");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_address0, "grp_keccak_absorb_fu_230_s_address0");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_ce0, "grp_keccak_absorb_fu_230_s_ce0");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_we0, "grp_keccak_absorb_fu_230_s_we0");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_d0, "grp_keccak_absorb_fu_230_s_d0");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_address1, "grp_keccak_absorb_fu_230_s_address1");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_ce1, "grp_keccak_absorb_fu_230_s_ce1");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_we1, "grp_keccak_absorb_fu_230_s_we1");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_s_d1, "grp_keccak_absorb_fu_230_s_d1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_ap_start, "grp_keccak_squeezeblocks_1_fu_241_ap_start");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_ap_done, "grp_keccak_squeezeblocks_1_fu_241_ap_done");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_ap_idle, "grp_keccak_squeezeblocks_1_fu_241_ap_idle");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_ap_ready, "grp_keccak_squeezeblocks_1_fu_241_ap_ready");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_out_r_address0, "grp_keccak_squeezeblocks_1_fu_241_out_r_address0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_out_r_ce0, "grp_keccak_squeezeblocks_1_fu_241_out_r_ce0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_out_r_we0, "grp_keccak_squeezeblocks_1_fu_241_out_r_we0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_out_r_d0, "grp_keccak_squeezeblocks_1_fu_241_out_r_d0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_address0, "grp_keccak_squeezeblocks_1_fu_241_s_address0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_ce0, "grp_keccak_squeezeblocks_1_fu_241_s_ce0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_we0, "grp_keccak_squeezeblocks_1_fu_241_s_we0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_d0, "grp_keccak_squeezeblocks_1_fu_241_s_d0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_address1, "grp_keccak_squeezeblocks_1_fu_241_s_address1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_ce1, "grp_keccak_squeezeblocks_1_fu_241_s_ce1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_we1, "grp_keccak_squeezeblocks_1_fu_241_s_we1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_s_d1, "grp_keccak_squeezeblocks_1_fu_241_s_d1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_ap_start, "grp_pqcrystals_dilithium_2_fu_247_ap_start");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_ap_done, "grp_pqcrystals_dilithium_2_fu_247_ap_done");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_ap_idle, "grp_pqcrystals_dilithium_2_fu_247_ap_idle");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_ap_ready, "grp_pqcrystals_dilithium_2_fu_247_ap_ready");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_r_coeffs_address0, "grp_pqcrystals_dilithium_2_fu_247_r_coeffs_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_r_coeffs_ce0, "grp_pqcrystals_dilithium_2_fu_247_r_coeffs_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_r_coeffs_we0, "grp_pqcrystals_dilithium_2_fu_247_r_coeffs_we0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_r_coeffs_d0, "grp_pqcrystals_dilithium_2_fu_247_r_coeffs_d0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_a_address0, "grp_pqcrystals_dilithium_2_fu_247_a_address0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_a_ce0, "grp_pqcrystals_dilithium_2_fu_247_a_ce0");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_a_address1, "grp_pqcrystals_dilithium_2_fu_247_a_address1");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_a_ce1, "grp_pqcrystals_dilithium_2_fu_247_a_ce1");
    sc_trace(mVcdFile, i_0_i_i_i_reg_208, "i_0_i_i_i_reg_208");
    sc_trace(mVcdFile, icmp_ln364_fu_269_p2, "icmp_ln364_fu_269_p2");
    sc_trace(mVcdFile, i_3_i_reg_219, "i_3_i_reg_219");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_keccak_absorb_fu_230_ap_start_reg, "grp_keccak_absorb_fu_230_ap_start_reg");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_241_ap_start_reg, "grp_keccak_squeezeblocks_1_fu_241_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, grp_pqcrystals_dilithium_2_fu_247_ap_start_reg, "grp_pqcrystals_dilithium_2_fu_247_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, zext_ln365_fu_281_p1, "zext_ln365_fu_281_p1");
    sc_trace(mVcdFile, zext_ln421_1_fu_321_p1, "zext_ln421_1_fu_321_p1");
    sc_trace(mVcdFile, zext_ln32_fu_332_p1, "zext_ln32_fu_332_p1");
    sc_trace(mVcdFile, zext_ln420_fu_286_p1, "zext_ln420_fu_286_p1");
    sc_trace(mVcdFile, zext_ln32_1_fu_345_p1, "zext_ln32_1_fu_345_p1");
    sc_trace(mVcdFile, zext_ln32_2_fu_355_p1, "zext_ln32_2_fu_355_p1");
    sc_trace(mVcdFile, zext_ln32_3_fu_365_p1, "zext_ln32_3_fu_365_p1");
    sc_trace(mVcdFile, zext_ln32_4_fu_375_p1, "zext_ln32_4_fu_375_p1");
    sc_trace(mVcdFile, zext_ln32_5_fu_385_p1, "zext_ln32_5_fu_385_p1");
    sc_trace(mVcdFile, zext_ln32_6_fu_395_p1, "zext_ln32_6_fu_395_p1");
    sc_trace(mVcdFile, zext_ln454_1_fu_431_p1, "zext_ln454_1_fu_431_p1");
    sc_trace(mVcdFile, xor_ln421_fu_414_p2, "xor_ln421_fu_414_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, xor_ln454_fu_457_p2, "xor_ln454_fu_457_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, xor_ln455_fu_464_p2, "xor_ln455_fu_464_p2");
    sc_trace(mVcdFile, shl_ln1_fu_303_p3, "shl_ln1_fu_303_p3");
    sc_trace(mVcdFile, add_ln421_fu_315_p2, "add_ln421_fu_315_p2");
    sc_trace(mVcdFile, add_ln32_fu_326_p2, "add_ln32_fu_326_p2");
    sc_trace(mVcdFile, add_ln32_1_fu_340_p2, "add_ln32_1_fu_340_p2");
    sc_trace(mVcdFile, add_ln32_2_fu_350_p2, "add_ln32_2_fu_350_p2");
    sc_trace(mVcdFile, add_ln32_3_fu_360_p2, "add_ln32_3_fu_360_p2");
    sc_trace(mVcdFile, add_ln32_4_fu_370_p2, "add_ln32_4_fu_370_p2");
    sc_trace(mVcdFile, add_ln32_5_fu_380_p2, "add_ln32_5_fu_380_p2");
    sc_trace(mVcdFile, add_ln32_6_fu_390_p2, "add_ln32_6_fu_390_p2");
    sc_trace(mVcdFile, r_7_i1_i_fu_400_p9, "r_7_i1_i_fu_400_p9");
    sc_trace(mVcdFile, i_fu_421_p4, "i_fu_421_p4");
    sc_trace(mVcdFile, trunc_ln454_fu_436_p1, "trunc_ln454_fu_436_p1");
    sc_trace(mVcdFile, shl_ln_fu_439_p3, "shl_ln_fu_439_p3");
    sc_trace(mVcdFile, zext_ln454_fu_447_p1, "zext_ln454_fu_447_p1");
    sc_trace(mVcdFile, shl_ln454_fu_451_p2, "shl_ln454_fu_451_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

pqcrystals_dilithium_9::~pqcrystals_dilithium_9() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buf_U;
    delete state_s_U;
    delete grp_keccak_absorb_fu_230;
    delete grp_keccak_squeezeblocks_1_fu_241;
    delete grp_pqcrystals_dilithium_2_fu_247;
}

void pqcrystals_dilithium_9::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv9_88;
}

void pqcrystals_dilithium_9::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv7_30;
}

void pqcrystals_dilithium_9::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_keccak_absorb_fu_230_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
             esl_seteq<1,1,1>(icmp_ln420_fu_291_p2.read(), ap_const_lv1_1))) {
            grp_keccak_absorb_fu_230_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_keccak_absorb_fu_230_ap_ready.read())) {
            grp_keccak_absorb_fu_230_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_keccak_squeezeblocks_1_fu_241_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
            grp_keccak_squeezeblocks_1_fu_241_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_keccak_squeezeblocks_1_fu_241_ap_ready.read())) {
            grp_keccak_squeezeblocks_1_fu_241_ap_start_reg = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_pqcrystals_dilithium_2_fu_247_ap_start_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
            grp_pqcrystals_dilithium_2_fu_247_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pqcrystals_dilithium_2_fu_247_ap_ready.read())) {
            grp_pqcrystals_dilithium_2_fu_247_ap_start_reg = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln364_fu_269_p2.read()))) {
        i_0_i_i_i_reg_208 = i_1_fu_275_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_i_i_i_reg_208 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln364_fu_269_p2.read()))) {
        i_3_i_reg_219 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i_3_i_reg_219 = add_ln420_reg_497.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln420_reg_497 = add_ln420_fu_297_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        seed_load_1_reg_537 = seed_q1.read();
        seed_load_reg_532 = seed_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        seed_load_2_reg_552 = seed_q0.read();
        seed_load_3_reg_557 = seed_q1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        seed_load_4_reg_572 = seed_q0.read();
        seed_load_5_reg_577 = seed_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_keccak_absorb_fu_230_ap_done.read(), ap_const_logic_1))) {
        state_pos_write_assi_reg_592 = grp_keccak_absorb_fu_230_ap_return.read();
        state_s_addr_1_reg_597 =  (sc_lv<5>) (zext_ln454_1_fu_431_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln420_fu_291_p2.read(), ap_const_lv1_0))) {
        state_s_addr_3_reg_522 =  (sc_lv<5>) (zext_ln420_fu_286_p1.read());
        zext_ln421_reg_502 = zext_ln421_fu_311_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        t_0_reg_476 = t_0_fu_255_p1.read();
        t_1_reg_481 = nonce.read().range(15, 8);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln420_fu_291_p2.read(), ap_const_lv1_1))) {
        trunc_ln503_reg_527 = trunc_ln503_fu_337_p1.read();
    }
}

void pqcrystals_dilithium_9::thread_a_coeffs_address0() {
    a_coeffs_address0 = grp_pqcrystals_dilithium_2_fu_247_r_coeffs_address0.read();
}

void pqcrystals_dilithium_9::thread_a_coeffs_ce0() {
    a_coeffs_ce0 = grp_pqcrystals_dilithium_2_fu_247_r_coeffs_ce0.read();
}

void pqcrystals_dilithium_9::thread_a_coeffs_d0() {
    a_coeffs_d0 = grp_pqcrystals_dilithium_2_fu_247_r_coeffs_d0.read();
}

void pqcrystals_dilithium_9::thread_a_coeffs_we0() {
    a_coeffs_we0 = grp_pqcrystals_dilithium_2_fu_247_r_coeffs_we0.read();
}

void pqcrystals_dilithium_9::thread_add_ln32_1_fu_340_p2() {
    add_ln32_1_fu_340_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A2.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A2));
}

void pqcrystals_dilithium_9::thread_add_ln32_2_fu_350_p2() {
    add_ln32_2_fu_350_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A3.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A3));
}

void pqcrystals_dilithium_9::thread_add_ln32_3_fu_360_p2() {
    add_ln32_3_fu_360_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A4.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A4));
}

void pqcrystals_dilithium_9::thread_add_ln32_4_fu_370_p2() {
    add_ln32_4_fu_370_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A5.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A5));
}

void pqcrystals_dilithium_9::thread_add_ln32_5_fu_380_p2() {
    add_ln32_5_fu_380_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A6.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A6));
}

void pqcrystals_dilithium_9::thread_add_ln32_6_fu_390_p2() {
    add_ln32_6_fu_390_p2 = (!zext_ln421_reg_502.read().is_01() || !ap_const_lv8_A7.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_reg_502.read()) + sc_bigint<8>(ap_const_lv8_A7));
}

void pqcrystals_dilithium_9::thread_add_ln32_fu_326_p2() {
    add_ln32_fu_326_p2 = (!zext_ln421_fu_311_p1.read().is_01() || !ap_const_lv8_A1.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_fu_311_p1.read()) + sc_bigint<8>(ap_const_lv8_A1));
}

void pqcrystals_dilithium_9::thread_add_ln420_fu_297_p2() {
    add_ln420_fu_297_p2 = (!i_3_i_reg_219.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_3_i_reg_219.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void pqcrystals_dilithium_9::thread_add_ln421_fu_315_p2() {
    add_ln421_fu_315_p2 = (!zext_ln421_fu_311_p1.read().is_01() || !ap_const_lv8_A0.is_01())? sc_lv<8>(): (sc_biguint<8>(zext_ln421_fu_311_p1.read()) + sc_bigint<8>(ap_const_lv8_A0));
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void pqcrystals_dilithium_9::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void pqcrystals_dilithium_9::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
          esl_seteq<1,1,1>(grp_pqcrystals_dilithium_2_fu_247_ap_done.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && 
         esl_seteq<1,1,1>(grp_pqcrystals_dilithium_2_fu_247_ap_done.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_buf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        buf_address0 = grp_pqcrystals_dilithium_2_fu_247_a_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buf_address0 = grp_keccak_squeezeblocks_1_fu_241_out_r_address0.read();
    } else {
        buf_address0 = "XXXXXXXXXX";
    }
}

void pqcrystals_dilithium_9::thread_buf_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        buf_ce0 = grp_pqcrystals_dilithium_2_fu_247_a_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buf_ce0 = grp_keccak_squeezeblocks_1_fu_241_out_r_ce0.read();
    } else {
        buf_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_buf_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        buf_ce1 = grp_pqcrystals_dilithium_2_fu_247_a_ce1.read();
    } else {
        buf_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_buf_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        buf_we0 = grp_keccak_squeezeblocks_1_fu_241_out_r_we0.read();
    } else {
        buf_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_grp_keccak_absorb_fu_230_ap_start() {
    grp_keccak_absorb_fu_230_ap_start = grp_keccak_absorb_fu_230_ap_start_reg.read();
}

void pqcrystals_dilithium_9::thread_grp_keccak_squeezeblocks_1_fu_241_ap_start() {
    grp_keccak_squeezeblocks_1_fu_241_ap_start = grp_keccak_squeezeblocks_1_fu_241_ap_start_reg.read();
}

void pqcrystals_dilithium_9::thread_grp_pqcrystals_dilithium_2_fu_247_ap_start() {
    grp_pqcrystals_dilithium_2_fu_247_ap_start = grp_pqcrystals_dilithium_2_fu_247_ap_start_reg.read();
}

void pqcrystals_dilithium_9::thread_i_1_fu_275_p2() {
    i_1_fu_275_p2 = (!i_0_i_i_i_reg_208.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i_i_i_reg_208.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void pqcrystals_dilithium_9::thread_i_fu_421_p4() {
    i_fu_421_p4 = grp_keccak_absorb_fu_230_ap_return.read().range(31, 3);
}

void pqcrystals_dilithium_9::thread_icmp_ln364_fu_269_p2() {
    icmp_ln364_fu_269_p2 = (!i_0_i_i_i_reg_208.read().is_01() || !ap_const_lv5_19.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_i_reg_208.read() == ap_const_lv5_19);
}

void pqcrystals_dilithium_9::thread_icmp_ln420_fu_291_p2() {
    icmp_ln420_fu_291_p2 = (!i_3_i_reg_219.read().is_01() || !ap_const_lv3_6.is_01())? sc_lv<1>(): sc_lv<1>(i_3_i_reg_219.read() == ap_const_lv3_6);
}

void pqcrystals_dilithium_9::thread_r_7_i1_i_fu_400_p9() {
    r_7_i1_i_fu_400_p9 = esl_concat<56,8>(esl_concat<48,8>(esl_concat<40,8>(esl_concat<32,8>(esl_concat<24,8>(esl_concat<16,8>(esl_concat<8,8>(seed_q1.read(), seed_q0.read()), seed_load_5_reg_577.read()), seed_load_4_reg_572.read()), seed_load_3_reg_557.read()), seed_load_2_reg_552.read()), seed_load_1_reg_537.read()), seed_load_reg_532.read());
}

void pqcrystals_dilithium_9::thread_seed_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        seed_address0 =  (sc_lv<8>) (zext_ln32_5_fu_385_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        seed_address0 =  (sc_lv<8>) (zext_ln32_3_fu_365_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        seed_address0 =  (sc_lv<8>) (zext_ln32_1_fu_345_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        seed_address0 =  (sc_lv<8>) (zext_ln421_1_fu_321_p1.read());
    } else {
        seed_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void pqcrystals_dilithium_9::thread_seed_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        seed_address1 =  (sc_lv<8>) (zext_ln32_6_fu_395_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        seed_address1 =  (sc_lv<8>) (zext_ln32_4_fu_375_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        seed_address1 =  (sc_lv<8>) (zext_ln32_2_fu_355_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        seed_address1 =  (sc_lv<8>) (zext_ln32_fu_332_p1.read());
    } else {
        seed_address1 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void pqcrystals_dilithium_9::thread_seed_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        seed_ce0 = ap_const_logic_1;
    } else {
        seed_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_seed_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        seed_ce1 = ap_const_logic_1;
    } else {
        seed_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_shl_ln1_fu_303_p3() {
    shl_ln1_fu_303_p3 = esl_concat<3,3>(i_3_i_reg_219.read(), ap_const_lv3_0);
}

void pqcrystals_dilithium_9::thread_shl_ln454_fu_451_p2() {
    shl_ln454_fu_451_p2 = (!zext_ln454_fu_447_p1.read().is_01())? sc_lv<64>(): ap_const_lv64_1F << (unsigned short)zext_ln454_fu_447_p1.read().to_uint();
}

void pqcrystals_dilithium_9::thread_shl_ln_fu_439_p3() {
    shl_ln_fu_439_p3 = esl_concat<3,3>(trunc_ln454_fu_436_p1.read(), ap_const_lv3_0);
}

void pqcrystals_dilithium_9::thread_state_s_addr_2_reg_602() {
    state_s_addr_2_reg_602 =  (sc_lv<5>) (ap_const_lv64_10);
}

void pqcrystals_dilithium_9::thread_state_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_s_address0 = state_s_addr_2_reg_602.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        state_s_address0 =  (sc_lv<5>) (ap_const_lv64_10);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        state_s_address0 = state_s_addr_1_reg_597.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        state_s_address0 = state_s_addr_3_reg_522.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_address0 =  (sc_lv<5>) (zext_ln365_fu_281_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_address0 = grp_keccak_squeezeblocks_1_fu_241_s_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_address0 = grp_keccak_absorb_fu_230_s_address0.read();
    } else {
        state_s_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void pqcrystals_dilithium_9::thread_state_s_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_address1 = grp_keccak_squeezeblocks_1_fu_241_s_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_address1 = grp_keccak_absorb_fu_230_s_address1.read();
    } else {
        state_s_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void pqcrystals_dilithium_9::thread_state_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        state_s_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_ce0 = grp_keccak_squeezeblocks_1_fu_241_s_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_ce0 = grp_keccak_absorb_fu_230_s_ce0.read();
    } else {
        state_s_ce0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_state_s_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_ce1 = grp_keccak_squeezeblocks_1_fu_241_s_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_ce1 = grp_keccak_absorb_fu_230_s_ce1.read();
    } else {
        state_s_ce1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_state_s_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        state_s_d0 = xor_ln455_fu_464_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        state_s_d0 = xor_ln454_fu_457_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_d0 = xor_ln421_fu_414_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_d0 = ap_const_lv64_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_d0 = grp_keccak_squeezeblocks_1_fu_241_s_d0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_d0 = grp_keccak_absorb_fu_230_s_d0.read();
    } else {
        state_s_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_9::thread_state_s_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_d1 = grp_keccak_squeezeblocks_1_fu_241_s_d1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_d1 = grp_keccak_absorb_fu_230_s_d1.read();
    } else {
        state_s_d1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void pqcrystals_dilithium_9::thread_state_s_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln364_fu_269_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        state_s_we0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_we0 = grp_keccak_squeezeblocks_1_fu_241_s_we0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_we0 = grp_keccak_absorb_fu_230_s_we0.read();
    } else {
        state_s_we0 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_state_s_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        state_s_we1 = grp_keccak_squeezeblocks_1_fu_241_s_we1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        state_s_we1 = grp_keccak_absorb_fu_230_s_we1.read();
    } else {
        state_s_we1 = ap_const_logic_0;
    }
}

void pqcrystals_dilithium_9::thread_t_0_fu_255_p1() {
    t_0_fu_255_p1 = nonce.read().range(8-1, 0);
}

void pqcrystals_dilithium_9::thread_trunc_ln454_fu_436_p1() {
    trunc_ln454_fu_436_p1 = state_pos_write_assi_reg_592.read().range(3-1, 0);
}

void pqcrystals_dilithium_9::thread_trunc_ln503_fu_337_p1() {
    trunc_ln503_fu_337_p1 = a_coeffs_offset.read().range(2-1, 0);
}

void pqcrystals_dilithium_9::thread_xor_ln421_fu_414_p2() {
    xor_ln421_fu_414_p2 = (state_s_q0.read() ^ r_7_i1_i_fu_400_p9.read());
}

void pqcrystals_dilithium_9::thread_xor_ln454_fu_457_p2() {
    xor_ln454_fu_457_p2 = (state_s_q0.read() ^ shl_ln454_fu_451_p2.read());
}

void pqcrystals_dilithium_9::thread_xor_ln455_fu_464_p2() {
    xor_ln455_fu_464_p2 = (state_s_q0.read() ^ ap_const_lv64_8000000000000000);
}

void pqcrystals_dilithium_9::thread_zext_ln32_1_fu_345_p1() {
    zext_ln32_1_fu_345_p1 = esl_zext<64,8>(add_ln32_1_fu_340_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_2_fu_355_p1() {
    zext_ln32_2_fu_355_p1 = esl_zext<64,8>(add_ln32_2_fu_350_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_3_fu_365_p1() {
    zext_ln32_3_fu_365_p1 = esl_zext<64,8>(add_ln32_3_fu_360_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_4_fu_375_p1() {
    zext_ln32_4_fu_375_p1 = esl_zext<64,8>(add_ln32_4_fu_370_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_5_fu_385_p1() {
    zext_ln32_5_fu_385_p1 = esl_zext<64,8>(add_ln32_5_fu_380_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_6_fu_395_p1() {
    zext_ln32_6_fu_395_p1 = esl_zext<64,8>(add_ln32_6_fu_390_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln32_fu_332_p1() {
    zext_ln32_fu_332_p1 = esl_zext<64,8>(add_ln32_fu_326_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln365_fu_281_p1() {
    zext_ln365_fu_281_p1 = esl_zext<64,5>(i_0_i_i_i_reg_208.read());
}

void pqcrystals_dilithium_9::thread_zext_ln420_fu_286_p1() {
    zext_ln420_fu_286_p1 = esl_zext<64,3>(i_3_i_reg_219.read());
}

void pqcrystals_dilithium_9::thread_zext_ln421_1_fu_321_p1() {
    zext_ln421_1_fu_321_p1 = esl_zext<64,8>(add_ln421_fu_315_p2.read());
}

void pqcrystals_dilithium_9::thread_zext_ln421_fu_311_p1() {
    zext_ln421_fu_311_p1 = esl_zext<8,6>(shl_ln1_fu_303_p3.read());
}

void pqcrystals_dilithium_9::thread_zext_ln454_1_fu_431_p1() {
    zext_ln454_1_fu_431_p1 = esl_zext<64,29>(i_fu_421_p4.read());
}

void pqcrystals_dilithium_9::thread_zext_ln454_fu_447_p1() {
    zext_ln454_fu_447_p1 = esl_zext<64,6>(shl_ln_fu_439_p3.read());
}

void pqcrystals_dilithium_9::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln364_fu_269_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln420_fu_291_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_keccak_absorb_fu_230_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(grp_keccak_squeezeblocks_1_fu_241_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(grp_pqcrystals_dilithium_2_fu_247_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

}

