// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "pqcrystals_dilithium_29.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic pqcrystals_dilithium_29::ap_const_logic_1 = sc_dt::Log_1;
const bool pqcrystals_dilithium_29::ap_const_boolean_1 = true;
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_7F = "1111111";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_7 = "111";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_1F = "11111";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_18 = "11000";
const sc_lv<9> pqcrystals_dilithium_29::ap_const_lv9_2B = "101011";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_8 = "1000";
const sc_lv<1> pqcrystals_dilithium_29::ap_const_lv1_1 = "1";
const sc_lv<8> pqcrystals_dilithium_29::ap_const_lv8_FF = "11111111";
const sc_lv<8> pqcrystals_dilithium_29::ap_const_lv8_0 = "00000000";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_3FF000 = "1111111111000000000000";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_7FE001 = "11111111110000000000001";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_2C0B = "10110000001011";
const sc_lv<32> pqcrystals_dilithium_29::ap_const_lv32_800000 = "100000000000000000000000";
const sc_lv<27> pqcrystals_dilithium_29::ap_const_lv27_7FD1800 = "111111111010001100000000000";
const sc_logic pqcrystals_dilithium_29::ap_const_logic_0 = sc_dt::Log_0;

pqcrystals_dilithium_29::pqcrystals_dilithium_29(sc_module_name name) : sc_module(name), mVcdFile(0) {
    crypto_sign_mac_mjbC_U88 = new crypto_sign_mac_mjbC<1,1,15,25,25,32>("crypto_sign_mac_mjbC_U88");
    crypto_sign_mac_mjbC_U88->din0(grp_fu_163_p0);
    crypto_sign_mac_mjbC_U88->din1(trunc_ln_fu_56_p4);
    crypto_sign_mac_mjbC_U88->din2(grp_fu_163_p2);
    crypto_sign_mac_mjbC_U88->dout(grp_fu_163_p3);
    crypto_sign_mac_mkbM_U89 = new crypto_sign_mac_mkbM<1,1,19,8,32,32>("crypto_sign_mac_mkbM_U89");
    crypto_sign_mac_mkbM_U89->din0(grp_fu_172_p0);
    crypto_sign_mac_mkbM_U89->din1(a1_1_fu_111_p2);
    crypto_sign_mac_mkbM_U89->din2(a);
    crypto_sign_mac_mkbM_U89->dout(grp_fu_172_p3);

    SC_METHOD(thread_a1_1_fu_111_p2);
    sensitive << ( trunc_ln5_fu_70_p4 );
    sensitive << ( select_ln48_fu_103_p3 );

    SC_METHOD(thread_add_ln42_fu_50_p2);
    sensitive << ( a );

    SC_METHOD(thread_ap_ready);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( sext_ln48_1_fu_121_p1 );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( sub_ln52_1_fu_146_p2 );

    SC_METHOD(thread_grp_fu_163_p0);

    SC_METHOD(thread_grp_fu_163_p2);

    SC_METHOD(thread_grp_fu_172_p0);

    SC_METHOD(thread_select_ln48_fu_103_p3);
    sensitive << ( xor_ln48_fu_97_p2 );

    SC_METHOD(thread_select_ln52_fu_138_p3);
    sensitive << ( tmp_637_fu_130_p3 );

    SC_METHOD(thread_sext_ln47_fu_79_p1);
    sensitive << ( trunc_ln5_fu_70_p4 );

    SC_METHOD(thread_sext_ln48_1_fu_121_p1);
    sensitive << ( a1_1_fu_111_p2 );

    SC_METHOD(thread_sub_ln48_fu_83_p2);
    sensitive << ( sext_ln47_fu_79_p1 );

    SC_METHOD(thread_sub_ln52_1_fu_146_p2);
    sensitive << ( grp_fu_172_p3 );
    sensitive << ( select_ln52_fu_138_p3 );

    SC_METHOD(thread_sub_ln52_fu_125_p2);
    sensitive << ( grp_fu_172_p3 );

    SC_METHOD(thread_tmp_637_fu_130_p3);
    sensitive << ( sub_ln52_fu_125_p2 );

    SC_METHOD(thread_tmp_fu_89_p3);
    sensitive << ( sub_ln48_fu_83_p2 );

    SC_METHOD(thread_trunc_ln5_fu_70_p4);
    sensitive << ( grp_fu_163_p3 );

    SC_METHOD(thread_trunc_ln_fu_56_p4);
    sensitive << ( add_ln42_fu_50_p2 );

    SC_METHOD(thread_xor_ln48_fu_97_p2);
    sensitive << ( tmp_fu_89_p3 );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "pqcrystals_dilithium_29_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a, "(port)a");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, add_ln42_fu_50_p2, "add_ln42_fu_50_p2");
    sc_trace(mVcdFile, trunc_ln_fu_56_p4, "trunc_ln_fu_56_p4");
    sc_trace(mVcdFile, grp_fu_163_p3, "grp_fu_163_p3");
    sc_trace(mVcdFile, trunc_ln5_fu_70_p4, "trunc_ln5_fu_70_p4");
    sc_trace(mVcdFile, sext_ln47_fu_79_p1, "sext_ln47_fu_79_p1");
    sc_trace(mVcdFile, sub_ln48_fu_83_p2, "sub_ln48_fu_83_p2");
    sc_trace(mVcdFile, tmp_fu_89_p3, "tmp_fu_89_p3");
    sc_trace(mVcdFile, xor_ln48_fu_97_p2, "xor_ln48_fu_97_p2");
    sc_trace(mVcdFile, select_ln48_fu_103_p3, "select_ln48_fu_103_p3");
    sc_trace(mVcdFile, a1_1_fu_111_p2, "a1_1_fu_111_p2");
    sc_trace(mVcdFile, grp_fu_172_p3, "grp_fu_172_p3");
    sc_trace(mVcdFile, sub_ln52_fu_125_p2, "sub_ln52_fu_125_p2");
    sc_trace(mVcdFile, tmp_637_fu_130_p3, "tmp_637_fu_130_p3");
    sc_trace(mVcdFile, select_ln52_fu_138_p3, "select_ln52_fu_138_p3");
    sc_trace(mVcdFile, sext_ln48_1_fu_121_p1, "sext_ln48_1_fu_121_p1");
    sc_trace(mVcdFile, sub_ln52_1_fu_146_p2, "sub_ln52_1_fu_146_p2");
    sc_trace(mVcdFile, grp_fu_163_p0, "grp_fu_163_p0");
    sc_trace(mVcdFile, grp_fu_163_p2, "grp_fu_163_p2");
    sc_trace(mVcdFile, grp_fu_172_p0, "grp_fu_172_p0");
#endif

    }
}

pqcrystals_dilithium_29::~pqcrystals_dilithium_29() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete crypto_sign_mac_mjbC_U88;
    delete crypto_sign_mac_mkbM_U89;
}

void pqcrystals_dilithium_29::thread_a1_1_fu_111_p2() {
    a1_1_fu_111_p2 = (select_ln48_fu_103_p3.read() & trunc_ln5_fu_70_p4.read());
}

void pqcrystals_dilithium_29::thread_add_ln42_fu_50_p2() {
    add_ln42_fu_50_p2 = (!ap_const_lv32_7F.is_01() || !a.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_7F) + sc_biguint<32>(a.read()));
}

void pqcrystals_dilithium_29::thread_ap_ready() {
    ap_ready = ap_const_logic_1;
}

void pqcrystals_dilithium_29::thread_ap_return_0() {
    ap_return_0 = sext_ln48_1_fu_121_p1.read();
}

void pqcrystals_dilithium_29::thread_ap_return_1() {
    ap_return_1 = sub_ln52_1_fu_146_p2.read();
}

void pqcrystals_dilithium_29::thread_grp_fu_163_p0() {
    grp_fu_163_p0 =  (sc_lv<15>) (ap_const_lv32_2C0B);
}

void pqcrystals_dilithium_29::thread_grp_fu_163_p2() {
    grp_fu_163_p2 =  (sc_lv<25>) (ap_const_lv32_800000);
}

void pqcrystals_dilithium_29::thread_grp_fu_172_p0() {
    grp_fu_172_p0 =  (sc_lv<19>) (ap_const_lv27_7FD1800);
}

void pqcrystals_dilithium_29::thread_select_ln48_fu_103_p3() {
    select_ln48_fu_103_p3 = (!xor_ln48_fu_97_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln48_fu_97_p2.read()[0].to_bool())? ap_const_lv8_FF: ap_const_lv8_0);
}

void pqcrystals_dilithium_29::thread_select_ln52_fu_138_p3() {
    select_ln52_fu_138_p3 = (!tmp_637_fu_130_p3.read()[0].is_01())? sc_lv<32>(): ((tmp_637_fu_130_p3.read()[0].to_bool())? ap_const_lv32_7FE001: ap_const_lv32_0);
}

void pqcrystals_dilithium_29::thread_sext_ln47_fu_79_p1() {
    sext_ln47_fu_79_p1 = esl_sext<9,8>(trunc_ln5_fu_70_p4.read());
}

void pqcrystals_dilithium_29::thread_sext_ln48_1_fu_121_p1() {
    sext_ln48_1_fu_121_p1 = esl_sext<32,8>(a1_1_fu_111_p2.read());
}

void pqcrystals_dilithium_29::thread_sub_ln48_fu_83_p2() {
    sub_ln48_fu_83_p2 = (!ap_const_lv9_2B.is_01() || !sext_ln47_fu_79_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_2B) - sc_bigint<9>(sext_ln47_fu_79_p1.read()));
}

void pqcrystals_dilithium_29::thread_sub_ln52_1_fu_146_p2() {
    sub_ln52_1_fu_146_p2 = (!grp_fu_172_p3.read().is_01() || !select_ln52_fu_138_p3.read().is_01())? sc_lv<32>(): (sc_bigint<32>(grp_fu_172_p3.read()) - sc_biguint<32>(select_ln52_fu_138_p3.read()));
}

void pqcrystals_dilithium_29::thread_sub_ln52_fu_125_p2() {
    sub_ln52_fu_125_p2 = (!ap_const_lv32_3FF000.is_01() || !grp_fu_172_p3.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_3FF000) - sc_bigint<32>(grp_fu_172_p3.read()));
}

void pqcrystals_dilithium_29::thread_tmp_637_fu_130_p3() {
    tmp_637_fu_130_p3 = sub_ln52_fu_125_p2.read().range(31, 31);
}

void pqcrystals_dilithium_29::thread_tmp_fu_89_p3() {
    tmp_fu_89_p3 = sub_ln48_fu_83_p2.read().range(8, 8);
}

void pqcrystals_dilithium_29::thread_trunc_ln5_fu_70_p4() {
    trunc_ln5_fu_70_p4 = grp_fu_163_p3.read().range(31, 24);
}

void pqcrystals_dilithium_29::thread_trunc_ln_fu_56_p4() {
    trunc_ln_fu_56_p4 = add_ln42_fu_50_p2.read().range(31, 7);
}

void pqcrystals_dilithium_29::thread_xor_ln48_fu_97_p2() {
    xor_ln48_fu_97_p2 = (tmp_fu_89_p3.read() ^ ap_const_lv1_1);
}

}

