-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity shake128_absorb is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    state_s_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    state_s_ce0 : OUT STD_LOGIC;
    state_s_we0 : OUT STD_LOGIC;
    state_s_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    state_s_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    in_0_read : IN STD_LOGIC_VECTOR (7 downto 0);
    in_1_read : IN STD_LOGIC_VECTOR (1 downto 0) );
end;


architecture behav of shake128_absorb is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (6 downto 0) := "0000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (6 downto 0) := "0000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (6 downto 0) := "0001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (6 downto 0) := "0010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (6 downto 0) := "0100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (6 downto 0) := "1000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_4 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal in_1_read_cast_fu_169_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal in_1_read_cast_reg_296 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln388_fu_173_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal i_fu_196_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_17_fu_218_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_18_fu_241_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_18_reg_328 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal icmp_ln30_fu_235_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal state_s_addr_reg_338 : STD_LOGIC_VECTOR (4 downto 0);
    signal r_fu_278_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal t_address0 : STD_LOGIC_VECTOR (2 downto 0);
    signal t_ce0 : STD_LOGIC;
    signal t_we0 : STD_LOGIC;
    signal t_d0 : STD_LOGIC_VECTOR (7 downto 0);
    signal t_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal phi_ln388_reg_112 : STD_LOGIC_VECTOR (2 downto 0);
    signal icmp_ln388_fu_184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_4_i_reg_123 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln424_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_5_i_reg_134 : STD_LOGIC_VECTOR (1 downto 0);
    signal icmp_ln426_fu_212_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal i_0_i2_reg_145 : STD_LOGIC_VECTOR (3 downto 0);
    signal r_0_i3_reg_157 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln388_fu_179_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln425_fu_202_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln426_fu_207_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln31_fu_247_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln427_fu_228_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal trunc_ln427_fu_224_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln31_fu_256_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal shl_ln_fu_260_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal zext_ln31_8_fu_252_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln31_9_fu_268_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal shl_ln31_fu_272_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (6 downto 0);

    component shake256_absorb_4_t IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (7 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;



begin
    t_U : component shake256_absorb_4_t
    generic map (
        DataWidth => 8,
        AddressRange => 8,
        AddressWidth => 3)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => t_address0,
        ce0 => t_ce0,
        we0 => t_we0,
        d0 => t_d0,
        q0 => t_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_i2_reg_145_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln426_fu_212_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_0_i2_reg_145 <= ap_const_lv4_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                i_0_i2_reg_145 <= i_18_reg_328;
            end if; 
        end if;
    end process;

    i_4_i_reg_123_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln388_fu_184_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                i_4_i_reg_123 <= ap_const_lv4_0;
            elsif (((icmp_ln424_fu_190_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_4_i_reg_123 <= i_fu_196_p2;
            end if; 
        end if;
    end process;

    i_5_i_reg_134_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln424_fu_190_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                i_5_i_reg_134 <= ap_const_lv2_0;
            elsif (((icmp_ln426_fu_212_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                i_5_i_reg_134 <= i_17_fu_218_p2;
            end if; 
        end if;
    end process;

    phi_ln388_reg_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln388_fu_184_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                phi_ln388_reg_112 <= add_ln388_fu_173_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                phi_ln388_reg_112 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    r_0_i3_reg_157_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln426_fu_212_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                r_0_i3_reg_157 <= ap_const_lv64_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                r_0_i3_reg_157 <= r_fu_278_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                i_18_reg_328 <= i_18_fu_241_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    in_1_read_cast_reg_296(1 downto 0) <= in_1_read_cast_fu_169_p1(1 downto 0);
            end if;
        end if;
    end process;
    in_1_read_cast_reg_296(7 downto 2) <= "000000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, icmp_ln30_fu_235_p2, icmp_ln388_fu_184_p2, icmp_ln424_fu_190_p2, icmp_ln426_fu_212_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln388_fu_184_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln424_fu_190_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((icmp_ln426_fu_212_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((icmp_ln30_fu_235_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXX";
        end case;
    end process;
    add_ln388_fu_173_p2 <= std_logic_vector(unsigned(phi_ln388_reg_112) + unsigned(ap_const_lv3_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_17_fu_218_p2 <= std_logic_vector(unsigned(i_5_i_reg_134) + unsigned(ap_const_lv2_1));
    i_18_fu_241_p2 <= std_logic_vector(unsigned(i_0_i2_reg_145) + unsigned(ap_const_lv4_1));
    i_fu_196_p2 <= std_logic_vector(unsigned(i_4_i_reg_123) + unsigned(ap_const_lv4_1));
    icmp_ln30_fu_235_p2 <= "1" when (i_0_i2_reg_145 = ap_const_lv4_8) else "0";
    icmp_ln388_fu_184_p2 <= "1" when (phi_ln388_reg_112 = ap_const_lv3_7) else "0";
    icmp_ln424_fu_190_p2 <= "1" when (i_4_i_reg_123 = ap_const_lv4_8) else "0";
    icmp_ln426_fu_212_p2 <= "1" when (i_5_i_reg_134 = ap_const_lv2_2) else "0";
    in_1_read_cast_fu_169_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(in_1_read),8));
    r_fu_278_p2 <= (shl_ln31_fu_272_p2 or r_0_i3_reg_157);
    select_ln427_fu_228_p3 <= 
        in_1_read_cast_reg_296 when (trunc_ln427_fu_224_p1(0) = '1') else 
        in_0_read;
    shl_ln31_fu_272_p2 <= std_logic_vector(shift_left(unsigned(zext_ln31_8_fu_252_p1),to_integer(unsigned('0' & zext_ln31_9_fu_268_p1(31-1 downto 0)))));
    shl_ln_fu_260_p3 <= (trunc_ln31_fu_256_p1 & ap_const_lv3_0);
    state_s_addr_reg_338 <= ap_const_lv64_4(5 - 1 downto 0);

    state_s_address0_assign_proc : process(ap_CS_fsm_state5, state_s_addr_reg_338, ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            state_s_address0 <= state_s_addr_reg_338;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            state_s_address0 <= ap_const_lv64_4(5 - 1 downto 0);
        else 
            state_s_address0 <= "XXXXX";
        end if; 
    end process;


    state_s_ce0_assign_proc : process(ap_CS_fsm_state5, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state7))) then 
            state_s_ce0 <= ap_const_logic_1;
        else 
            state_s_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    state_s_d0 <= (state_s_q0 xor r_0_i3_reg_157);

    state_s_we0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            state_s_we0 <= ap_const_logic_1;
        else 
            state_s_we0 <= ap_const_logic_0;
        end if; 
    end process;


    t_address0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, zext_ln388_fu_179_p1, zext_ln425_fu_202_p1, zext_ln426_fu_207_p1, zext_ln31_fu_247_p1)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            t_address0 <= zext_ln31_fu_247_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            t_address0 <= zext_ln426_fu_207_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            t_address0 <= zext_ln425_fu_202_p1(3 - 1 downto 0);
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            t_address0 <= zext_ln388_fu_179_p1(3 - 1 downto 0);
        else 
            t_address0 <= "XXX";
        end if; 
    end process;


    t_ce0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            t_ce0 <= ap_const_logic_1;
        else 
            t_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    t_d0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, select_ln427_fu_228_p3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            t_d0 <= select_ln427_fu_228_p3;
        elsif (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            t_d0 <= ap_const_lv8_0;
        else 
            t_d0 <= "XXXXXXXX";
        end if; 
    end process;


    t_we0_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_state3, ap_CS_fsm_state4, icmp_ln424_fu_190_p2, icmp_ln426_fu_212_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((icmp_ln426_fu_212_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((icmp_ln424_fu_190_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then 
            t_we0 <= ap_const_logic_1;
        else 
            t_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln31_fu_256_p1 <= i_0_i2_reg_145(3 - 1 downto 0);
    trunc_ln427_fu_224_p1 <= i_5_i_reg_134(1 - 1 downto 0);
    zext_ln31_8_fu_252_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(t_q0),64));
    zext_ln31_9_fu_268_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_260_p3),64));
    zext_ln31_fu_247_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_0_i2_reg_145),64));
    zext_ln388_fu_179_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(phi_ln388_reg_112),64));
    zext_ln425_fu_202_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_4_i_reg_123),64));
    zext_ln426_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(i_5_i_reg_134),64));
end behav;
