// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "poly_challenge.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic poly_challenge::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic poly_challenge::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<19> poly_challenge::ap_ST_fsm_state1 = "1";
const sc_lv<19> poly_challenge::ap_ST_fsm_state2 = "10";
const sc_lv<19> poly_challenge::ap_ST_fsm_state3 = "100";
const sc_lv<19> poly_challenge::ap_ST_fsm_state4 = "1000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state5 = "10000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state6 = "100000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state7 = "1000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state8 = "10000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state9 = "100000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state10 = "1000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state11 = "10000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state12 = "100000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<19> poly_challenge::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<32> poly_challenge::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> poly_challenge::ap_const_lv32_1 = "1";
const sc_lv<32> poly_challenge::ap_const_lv32_2 = "10";
const sc_lv<1> poly_challenge::ap_const_lv1_0 = "0";
const sc_lv<1> poly_challenge::ap_const_lv1_1 = "1";
const sc_lv<32> poly_challenge::ap_const_lv32_3 = "11";
const sc_lv<32> poly_challenge::ap_const_lv32_4 = "100";
const sc_lv<32> poly_challenge::ap_const_lv32_9 = "1001";
const sc_lv<32> poly_challenge::ap_const_lv32_A = "1010";
const sc_lv<32> poly_challenge::ap_const_lv32_B = "1011";
const sc_lv<32> poly_challenge::ap_const_lv32_D = "1101";
const sc_lv<32> poly_challenge::ap_const_lv32_F = "1111";
const sc_lv<32> poly_challenge::ap_const_lv32_10 = "10000";
const sc_lv<32> poly_challenge::ap_const_lv32_11 = "10001";
const sc_lv<5> poly_challenge::ap_const_lv5_0 = "00000";
const sc_lv<32> poly_challenge::ap_const_lv32_5 = "101";
const sc_lv<3> poly_challenge::ap_const_lv3_0 = "000";
const sc_lv<4> poly_challenge::ap_const_lv4_0 = "0000";
const sc_lv<64> poly_challenge::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<32> poly_challenge::ap_const_lv32_8 = "1000";
const sc_lv<9> poly_challenge::ap_const_lv9_0 = "000000000";
const sc_lv<32> poly_challenge::ap_const_lv32_12 = "10010";
const sc_lv<9> poly_challenge::ap_const_lv9_D9 = "11011001";
const sc_lv<32> poly_challenge::ap_const_lv32_C = "1100";
const sc_lv<32> poly_challenge::ap_const_lv32_E = "1110";
const bool poly_challenge::ap_const_boolean_0 = false;
const sc_lv<32> poly_challenge::ap_const_lv32_7 = "111";
const sc_lv<64> poly_challenge::ap_const_lv64_4 = "100";
const sc_lv<64> poly_challenge::ap_const_lv64_10 = "10000";
const sc_lv<32> poly_challenge::ap_const_lv32_6 = "110";
const sc_lv<5> poly_challenge::ap_const_lv5_19 = "11001";
const sc_lv<5> poly_challenge::ap_const_lv5_1 = "1";
const sc_lv<3> poly_challenge::ap_const_lv3_4 = "100";
const sc_lv<3> poly_challenge::ap_const_lv3_1 = "1";
const sc_lv<4> poly_challenge::ap_const_lv4_8 = "1000";
const sc_lv<4> poly_challenge::ap_const_lv4_1 = "1";
const sc_lv<64> poly_challenge::ap_const_lv64_1F = "11111";
const sc_lv<64> poly_challenge::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<9> poly_challenge::ap_const_lv9_100 = "100000000";
const sc_lv<9> poly_challenge::ap_const_lv9_1 = "1";
const sc_lv<32> poly_challenge::ap_const_lv32_87 = "10000111";
const sc_lv<32> poly_challenge::ap_const_lv32_3F = "111111";
const sc_lv<2> poly_challenge::ap_const_lv2_1 = "1";
const bool poly_challenge::ap_const_boolean_1 = true;

poly_challenge::poly_challenge(sc_module_name name) : sc_module(name), mVcdFile(0) {
    buf_U = new poly_challenge_buf("buf_U");
    buf_U->clk(ap_clk);
    buf_U->reset(ap_rst);
    buf_U->address0(buf_address0);
    buf_U->ce0(buf_ce0);
    buf_U->we0(buf_we0);
    buf_U->d0(grp_keccak_squeezeblocks_1_fu_328_out_r_d0);
    buf_U->q0(buf_q0);
    state_s_U = new poly_uniform_statdEe("state_s_U");
    state_s_U->clk(ap_clk);
    state_s_U->reset(ap_rst);
    state_s_U->address0(state_s_address0);
    state_s_U->ce0(state_s_ce0);
    state_s_U->we0(state_s_we0);
    state_s_U->d0(state_s_d0);
    state_s_U->q0(state_s_q0);
    state_s_U->address1(state_s_address1);
    state_s_U->ce1(state_s_ce1);
    state_s_U->we1(state_s_we1);
    state_s_U->d1(state_s_d1);
    state_s_U->q1(state_s_q1);
    grp_keccak_squeezeblocks_1_fu_328 = new keccak_squeezeblocks_1("grp_keccak_squeezeblocks_1_fu_328");
    grp_keccak_squeezeblocks_1_fu_328->ap_clk(ap_clk);
    grp_keccak_squeezeblocks_1_fu_328->ap_rst(ap_rst);
    grp_keccak_squeezeblocks_1_fu_328->ap_start(grp_keccak_squeezeblocks_1_fu_328_ap_start);
    grp_keccak_squeezeblocks_1_fu_328->ap_done(grp_keccak_squeezeblocks_1_fu_328_ap_done);
    grp_keccak_squeezeblocks_1_fu_328->ap_idle(grp_keccak_squeezeblocks_1_fu_328_ap_idle);
    grp_keccak_squeezeblocks_1_fu_328->ap_ready(grp_keccak_squeezeblocks_1_fu_328_ap_ready);
    grp_keccak_squeezeblocks_1_fu_328->out_r_address0(grp_keccak_squeezeblocks_1_fu_328_out_r_address0);
    grp_keccak_squeezeblocks_1_fu_328->out_r_ce0(grp_keccak_squeezeblocks_1_fu_328_out_r_ce0);
    grp_keccak_squeezeblocks_1_fu_328->out_r_we0(grp_keccak_squeezeblocks_1_fu_328_out_r_we0);
    grp_keccak_squeezeblocks_1_fu_328->out_r_d0(grp_keccak_squeezeblocks_1_fu_328_out_r_d0);
    grp_keccak_squeezeblocks_1_fu_328->s_address0(grp_keccak_squeezeblocks_1_fu_328_s_address0);
    grp_keccak_squeezeblocks_1_fu_328->s_ce0(grp_keccak_squeezeblocks_1_fu_328_s_ce0);
    grp_keccak_squeezeblocks_1_fu_328->s_we0(grp_keccak_squeezeblocks_1_fu_328_s_we0);
    grp_keccak_squeezeblocks_1_fu_328->s_d0(grp_keccak_squeezeblocks_1_fu_328_s_d0);
    grp_keccak_squeezeblocks_1_fu_328->s_q0(state_s_q0);
    grp_keccak_squeezeblocks_1_fu_328->s_address1(grp_keccak_squeezeblocks_1_fu_328_s_address1);
    grp_keccak_squeezeblocks_1_fu_328->s_ce1(grp_keccak_squeezeblocks_1_fu_328_s_ce1);
    grp_keccak_squeezeblocks_1_fu_328->s_we1(grp_keccak_squeezeblocks_1_fu_328_s_we1);
    grp_keccak_squeezeblocks_1_fu_328->s_d1(grp_keccak_squeezeblocks_1_fu_328_s_d1);
    grp_keccak_squeezeblocks_1_fu_328->s_q1(state_s_q1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_add_ln31_fu_397_p2);
    sensitive << ( shl_ln_reg_632 );
    sensitive << ( zext_ln31_fu_393_p1 );

    SC_METHOD(thread_add_ln417_fu_363_p2);
    sensitive << ( i_3_i_i_reg_200 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state15_on_subcall_done);
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_ap_done );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln529_fu_526_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln529_fu_526_p2 );

    SC_METHOD(thread_buf_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_out_r_address0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln524_fu_472_p1 );
    sensitive << ( zext_ln536_fu_544_p1 );

    SC_METHOD(thread_buf_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_out_r_ce0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_buf_we0);
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_out_r_we0 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_c_coeffs_address0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( c_coeffs_addr_1_reg_720 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( zext_ln528_fu_521_p1 );
    sensitive << ( zext_ln539_fu_559_p1 );
    sensitive << ( zext_ln539_1_fu_582_p1 );

    SC_METHOD(thread_c_coeffs_ce0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_c_coeffs_d0);
    sensitive << ( c_coeffs_q0 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( sext_ln540_fu_606_p1 );

    SC_METHOD(thread_c_coeffs_we0);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( icmp_ln527_fu_509_p2 );
    sensitive << ( ap_CS_fsm_state19 );

    SC_METHOD(thread_grp_keccak_squeezeblocks_1_fu_328_ap_start);
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_ap_start_reg );

    SC_METHOD(thread_i_32_fu_342_p2);
    sensitive << ( i_0_i_i_reg_189 );

    SC_METHOD(thread_i_33_fu_387_p2);
    sensitive << ( i_0_i1_i_reg_211 );

    SC_METHOD(thread_i_34_fu_515_p2);
    sensitive << ( i_1_reg_259 );

    SC_METHOD(thread_i_35_fu_587_p2);
    sensitive << ( i_2_reg_270 );

    SC_METHOD(thread_i_fu_466_p2);
    sensitive << ( i_0_reg_235 );

    SC_METHOD(thread_icmp_ln30_fu_381_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( i_0_i1_i_reg_211 );

    SC_METHOD(thread_icmp_ln362_fu_336_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_i_i_reg_189 );

    SC_METHOD(thread_icmp_ln417_fu_357_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( i_3_i_i_reg_200 );

    SC_METHOD(thread_icmp_ln523_fu_460_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( i_0_reg_235 );

    SC_METHOD(thread_icmp_ln527_fu_509_p2);
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( i_1_reg_259 );

    SC_METHOD(thread_icmp_ln529_fu_526_p2);
    sensitive << ( i_2_reg_270 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_icmp_ln531_fu_532_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( pos_1_reg_305 );

    SC_METHOD(thread_icmp_ln537_fu_553_p2);
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( i_2_reg_270 );
    sensitive << ( zext_ln536_1_fu_549_p1 );

    SC_METHOD(thread_pos_fu_538_p2);
    sensitive << ( pos_2_reg_316 );

    SC_METHOD(thread_r_fu_433_p2);
    sensitive << ( r_0_i2_i_reg_223 );
    sensitive << ( shl_ln31_fu_427_p2 );

    SC_METHOD(thread_seed_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln31_15_fu_402_p1 );

    SC_METHOD(thread_seed_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_sext_ln540_fu_606_p1);
    sensitive << ( sub_ln540_fu_600_p2 );

    SC_METHOD(thread_shl_ln15_fu_485_p3);
    sensitive << ( trunc_ln524_fu_481_p1 );

    SC_METHOD(thread_shl_ln16_fu_415_p3);
    sensitive << ( trunc_ln31_fu_411_p1 );

    SC_METHOD(thread_shl_ln17_fu_593_p3);
    sensitive << ( trunc_ln540_reg_725 );

    SC_METHOD(thread_shl_ln31_fu_427_p2);
    sensitive << ( zext_ln31_16_fu_407_p1 );
    sensitive << ( zext_ln31_17_fu_423_p1 );

    SC_METHOD(thread_shl_ln524_fu_497_p2);
    sensitive << ( zext_ln524_1_fu_477_p1 );
    sensitive << ( zext_ln524_2_fu_493_p1 );

    SC_METHOD(thread_shl_ln_fu_373_p3);
    sensitive << ( trunc_ln418_fu_369_p1 );

    SC_METHOD(thread_signs_2_fu_568_p4);
    sensitive << ( signs_1_reg_294 );

    SC_METHOD(thread_signs_3_fu_578_p1);
    sensitive << ( signs_2_fu_568_p4 );

    SC_METHOD(thread_signs_fu_503_p2);
    sensitive << ( signs_0_reg_247 );
    sensitive << ( shl_ln524_fu_497_p2 );

    SC_METHOD(thread_state_s_address0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( state_s_addr_12_reg_662 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln363_fu_348_p1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_s_address1);
    sensitive << ( zext_ln417_reg_619 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_address1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_s_ce0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_s_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_ce1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_s_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_d0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( xor_ln418_fu_439_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( xor_ln452_fu_453_p2 );

    SC_METHOD(thread_state_s_d1);
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_d1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( xor_ln451_fu_446_p2 );

    SC_METHOD(thread_state_s_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_we0 );
    sensitive << ( icmp_ln362_fu_336_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_state_s_we1);
    sensitive << ( icmp_ln531_reg_702 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_s_we1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_sub_ln540_fu_600_p2);
    sensitive << ( shl_ln17_fu_593_p3 );

    SC_METHOD(thread_trunc_ln31_fu_411_p1);
    sensitive << ( i_0_i1_i_reg_211 );

    SC_METHOD(thread_trunc_ln418_fu_369_p1);
    sensitive << ( i_3_i_i_reg_200 );

    SC_METHOD(thread_trunc_ln524_fu_481_p1);
    sensitive << ( i_0_reg_235 );

    SC_METHOD(thread_trunc_ln540_fu_564_p1);
    sensitive << ( signs_1_reg_294 );

    SC_METHOD(thread_xor_ln418_fu_439_p2);
    sensitive << ( state_s_q1 );
    sensitive << ( r_0_i2_i_reg_223 );

    SC_METHOD(thread_xor_ln451_fu_446_p2);
    sensitive << ( state_s_q0 );

    SC_METHOD(thread_xor_ln452_fu_453_p2);
    sensitive << ( state_s_q1 );

    SC_METHOD(thread_zext_ln31_15_fu_402_p1);
    sensitive << ( add_ln31_fu_397_p2 );

    SC_METHOD(thread_zext_ln31_16_fu_407_p1);
    sensitive << ( seed_q0 );

    SC_METHOD(thread_zext_ln31_17_fu_423_p1);
    sensitive << ( shl_ln16_fu_415_p3 );

    SC_METHOD(thread_zext_ln31_fu_393_p1);
    sensitive << ( i_0_i1_i_reg_211 );

    SC_METHOD(thread_zext_ln363_fu_348_p1);
    sensitive << ( i_0_i_i_reg_189 );

    SC_METHOD(thread_zext_ln417_fu_353_p1);
    sensitive << ( i_3_i_i_reg_200 );

    SC_METHOD(thread_zext_ln524_1_fu_477_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_zext_ln524_2_fu_493_p1);
    sensitive << ( shl_ln15_fu_485_p3 );

    SC_METHOD(thread_zext_ln524_fu_472_p1);
    sensitive << ( i_0_reg_235 );

    SC_METHOD(thread_zext_ln528_fu_521_p1);
    sensitive << ( i_1_reg_259 );

    SC_METHOD(thread_zext_ln536_1_fu_549_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_zext_ln536_fu_544_p1);
    sensitive << ( pos_2_reg_316 );

    SC_METHOD(thread_zext_ln539_1_fu_582_p1);
    sensitive << ( i_2_reg_270 );

    SC_METHOD(thread_zext_ln539_fu_559_p1);
    sensitive << ( buf_q0 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln417_fu_357_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( icmp_ln30_fu_381_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln523_fu_460_p2 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( icmp_ln537_fu_553_p2 );
    sensitive << ( grp_keccak_squeezeblocks_1_fu_328_ap_done );
    sensitive << ( icmp_ln362_fu_336_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln527_fu_509_p2 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( icmp_ln529_fu_526_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_block_state15_on_subcall_done );

    ap_CS_fsm = "0000000000000000001";
    grp_keccak_squeezeblocks_1_fu_328_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "poly_challenge_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, c_coeffs_address0, "(port)c_coeffs_address0");
    sc_trace(mVcdFile, c_coeffs_ce0, "(port)c_coeffs_ce0");
    sc_trace(mVcdFile, c_coeffs_we0, "(port)c_coeffs_we0");
    sc_trace(mVcdFile, c_coeffs_d0, "(port)c_coeffs_d0");
    sc_trace(mVcdFile, c_coeffs_q0, "(port)c_coeffs_q0");
    sc_trace(mVcdFile, seed_address0, "(port)seed_address0");
    sc_trace(mVcdFile, seed_ce0, "(port)seed_ce0");
    sc_trace(mVcdFile, seed_q0, "(port)seed_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_32_fu_342_p2, "i_32_fu_342_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, zext_ln417_fu_353_p1, "zext_ln417_fu_353_p1");
    sc_trace(mVcdFile, zext_ln417_reg_619, "zext_ln417_reg_619");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, add_ln417_fu_363_p2, "add_ln417_fu_363_p2");
    sc_trace(mVcdFile, add_ln417_reg_627, "add_ln417_reg_627");
    sc_trace(mVcdFile, shl_ln_fu_373_p3, "shl_ln_fu_373_p3");
    sc_trace(mVcdFile, shl_ln_reg_632, "shl_ln_reg_632");
    sc_trace(mVcdFile, icmp_ln417_fu_357_p2, "icmp_ln417_fu_357_p2");
    sc_trace(mVcdFile, i_33_fu_387_p2, "i_33_fu_387_p2");
    sc_trace(mVcdFile, i_33_reg_652, "i_33_reg_652");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln30_fu_381_p2, "icmp_ln30_fu_381_p2");
    sc_trace(mVcdFile, state_s_addr_12_reg_662, "state_s_addr_12_reg_662");
    sc_trace(mVcdFile, r_fu_433_p2, "r_fu_433_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, i_fu_466_p2, "i_fu_466_p2");
    sc_trace(mVcdFile, i_reg_676, "i_reg_676");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln523_fu_460_p2, "icmp_ln523_fu_460_p2");
    sc_trace(mVcdFile, signs_fu_503_p2, "signs_fu_503_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, i_34_fu_515_p2, "i_34_fu_515_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, icmp_ln531_fu_532_p2, "icmp_ln531_fu_532_p2");
    sc_trace(mVcdFile, icmp_ln531_reg_702, "icmp_ln531_reg_702");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, pos_fu_538_p2, "pos_fu_538_p2");
    sc_trace(mVcdFile, pos_reg_706, "pos_reg_706");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, c_coeffs_addr_1_reg_720, "c_coeffs_addr_1_reg_720");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, icmp_ln537_fu_553_p2, "icmp_ln537_fu_553_p2");
    sc_trace(mVcdFile, trunc_ln540_fu_564_p1, "trunc_ln540_fu_564_p1");
    sc_trace(mVcdFile, trunc_ln540_reg_725, "trunc_ln540_reg_725");
    sc_trace(mVcdFile, signs_3_fu_578_p1, "signs_3_fu_578_p1");
    sc_trace(mVcdFile, signs_3_reg_730, "signs_3_reg_730");
    sc_trace(mVcdFile, i_35_fu_587_p2, "i_35_fu_587_p2");
    sc_trace(mVcdFile, i_35_reg_735, "i_35_reg_735");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, buf_address0, "buf_address0");
    sc_trace(mVcdFile, buf_ce0, "buf_ce0");
    sc_trace(mVcdFile, buf_we0, "buf_we0");
    sc_trace(mVcdFile, buf_q0, "buf_q0");
    sc_trace(mVcdFile, state_s_address0, "state_s_address0");
    sc_trace(mVcdFile, state_s_ce0, "state_s_ce0");
    sc_trace(mVcdFile, state_s_we0, "state_s_we0");
    sc_trace(mVcdFile, state_s_d0, "state_s_d0");
    sc_trace(mVcdFile, state_s_q0, "state_s_q0");
    sc_trace(mVcdFile, state_s_address1, "state_s_address1");
    sc_trace(mVcdFile, state_s_ce1, "state_s_ce1");
    sc_trace(mVcdFile, state_s_we1, "state_s_we1");
    sc_trace(mVcdFile, state_s_d1, "state_s_d1");
    sc_trace(mVcdFile, state_s_q1, "state_s_q1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_ap_start, "grp_keccak_squeezeblocks_1_fu_328_ap_start");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_ap_done, "grp_keccak_squeezeblocks_1_fu_328_ap_done");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_ap_idle, "grp_keccak_squeezeblocks_1_fu_328_ap_idle");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_ap_ready, "grp_keccak_squeezeblocks_1_fu_328_ap_ready");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_out_r_address0, "grp_keccak_squeezeblocks_1_fu_328_out_r_address0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_out_r_ce0, "grp_keccak_squeezeblocks_1_fu_328_out_r_ce0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_out_r_we0, "grp_keccak_squeezeblocks_1_fu_328_out_r_we0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_out_r_d0, "grp_keccak_squeezeblocks_1_fu_328_out_r_d0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_address0, "grp_keccak_squeezeblocks_1_fu_328_s_address0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_ce0, "grp_keccak_squeezeblocks_1_fu_328_s_ce0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_we0, "grp_keccak_squeezeblocks_1_fu_328_s_we0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_d0, "grp_keccak_squeezeblocks_1_fu_328_s_d0");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_address1, "grp_keccak_squeezeblocks_1_fu_328_s_address1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_ce1, "grp_keccak_squeezeblocks_1_fu_328_s_ce1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_we1, "grp_keccak_squeezeblocks_1_fu_328_s_we1");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_s_d1, "grp_keccak_squeezeblocks_1_fu_328_s_d1");
    sc_trace(mVcdFile, i_0_i_i_reg_189, "i_0_i_i_reg_189");
    sc_trace(mVcdFile, icmp_ln362_fu_336_p2, "icmp_ln362_fu_336_p2");
    sc_trace(mVcdFile, i_3_i_i_reg_200, "i_3_i_i_reg_200");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, i_0_i1_i_reg_211, "i_0_i1_i_reg_211");
    sc_trace(mVcdFile, r_0_i2_i_reg_223, "r_0_i2_i_reg_223");
    sc_trace(mVcdFile, i_0_reg_235, "i_0_reg_235");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, signs_0_reg_247, "signs_0_reg_247");
    sc_trace(mVcdFile, i_1_reg_259, "i_1_reg_259");
    sc_trace(mVcdFile, icmp_ln527_fu_509_p2, "icmp_ln527_fu_509_p2");
    sc_trace(mVcdFile, i_2_reg_270, "i_2_reg_270");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, pos_0_reg_282, "pos_0_reg_282");
    sc_trace(mVcdFile, signs_1_reg_294, "signs_1_reg_294");
    sc_trace(mVcdFile, pos_1_reg_305, "pos_1_reg_305");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, icmp_ln529_fu_526_p2, "icmp_ln529_fu_526_p2");
    sc_trace(mVcdFile, pos_2_reg_316, "pos_2_reg_316");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_block_state15_on_subcall_done, "ap_block_state15_on_subcall_done");
    sc_trace(mVcdFile, grp_keccak_squeezeblocks_1_fu_328_ap_start_reg, "grp_keccak_squeezeblocks_1_fu_328_ap_start_reg");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, zext_ln363_fu_348_p1, "zext_ln363_fu_348_p1");
    sc_trace(mVcdFile, zext_ln31_15_fu_402_p1, "zext_ln31_15_fu_402_p1");
    sc_trace(mVcdFile, zext_ln524_fu_472_p1, "zext_ln524_fu_472_p1");
    sc_trace(mVcdFile, zext_ln528_fu_521_p1, "zext_ln528_fu_521_p1");
    sc_trace(mVcdFile, zext_ln536_fu_544_p1, "zext_ln536_fu_544_p1");
    sc_trace(mVcdFile, zext_ln539_fu_559_p1, "zext_ln539_fu_559_p1");
    sc_trace(mVcdFile, zext_ln539_1_fu_582_p1, "zext_ln539_1_fu_582_p1");
    sc_trace(mVcdFile, xor_ln418_fu_439_p2, "xor_ln418_fu_439_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, xor_ln451_fu_446_p2, "xor_ln451_fu_446_p2");
    sc_trace(mVcdFile, xor_ln452_fu_453_p2, "xor_ln452_fu_453_p2");
    sc_trace(mVcdFile, sext_ln540_fu_606_p1, "sext_ln540_fu_606_p1");
    sc_trace(mVcdFile, trunc_ln418_fu_369_p1, "trunc_ln418_fu_369_p1");
    sc_trace(mVcdFile, zext_ln31_fu_393_p1, "zext_ln31_fu_393_p1");
    sc_trace(mVcdFile, add_ln31_fu_397_p2, "add_ln31_fu_397_p2");
    sc_trace(mVcdFile, trunc_ln31_fu_411_p1, "trunc_ln31_fu_411_p1");
    sc_trace(mVcdFile, shl_ln16_fu_415_p3, "shl_ln16_fu_415_p3");
    sc_trace(mVcdFile, zext_ln31_16_fu_407_p1, "zext_ln31_16_fu_407_p1");
    sc_trace(mVcdFile, zext_ln31_17_fu_423_p1, "zext_ln31_17_fu_423_p1");
    sc_trace(mVcdFile, shl_ln31_fu_427_p2, "shl_ln31_fu_427_p2");
    sc_trace(mVcdFile, trunc_ln524_fu_481_p1, "trunc_ln524_fu_481_p1");
    sc_trace(mVcdFile, shl_ln15_fu_485_p3, "shl_ln15_fu_485_p3");
    sc_trace(mVcdFile, zext_ln524_1_fu_477_p1, "zext_ln524_1_fu_477_p1");
    sc_trace(mVcdFile, zext_ln524_2_fu_493_p1, "zext_ln524_2_fu_493_p1");
    sc_trace(mVcdFile, shl_ln524_fu_497_p2, "shl_ln524_fu_497_p2");
    sc_trace(mVcdFile, zext_ln536_1_fu_549_p1, "zext_ln536_1_fu_549_p1");
    sc_trace(mVcdFile, signs_2_fu_568_p4, "signs_2_fu_568_p4");
    sc_trace(mVcdFile, shl_ln17_fu_593_p3, "shl_ln17_fu_593_p3");
    sc_trace(mVcdFile, sub_ln540_fu_600_p2, "sub_ln540_fu_600_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

poly_challenge::~poly_challenge() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete buf_U;
    delete state_s_U;
    delete grp_keccak_squeezeblocks_1_fu_328;
}

void poly_challenge::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_keccak_squeezeblocks_1_fu_328_ap_start_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_fu_532_p2.read())))) {
            grp_keccak_squeezeblocks_1_fu_328_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_keccak_squeezeblocks_1_fu_328_ap_ready.read())) {
            grp_keccak_squeezeblocks_1_fu_328_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_0_i1_i_reg_211 = i_33_reg_652.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln417_fu_357_p2.read(), ap_const_lv1_0))) {
        i_0_i1_i_reg_211 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln362_fu_336_p2.read()))) {
        i_0_i_i_reg_189 = i_32_fu_342_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_i_i_reg_189 = ap_const_lv5_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_0_reg_235 = i_reg_676.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(grp_keccak_squeezeblocks_1_fu_328_ap_done.read(), ap_const_logic_1))) {
        i_0_reg_235 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln523_fu_460_p2.read()))) {
        i_1_reg_259 = ap_const_lv9_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln527_fu_509_p2.read()))) {
        i_1_reg_259 = i_34_fu_515_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln527_fu_509_p2.read()))) {
        i_2_reg_270 = ap_const_lv9_D9;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        i_2_reg_270 = i_35_reg_735.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln362_fu_336_p2.read()))) {
        i_3_i_i_reg_200 = ap_const_lv3_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        i_3_i_i_reg_200 = add_ln417_reg_627.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln527_fu_509_p2.read()))) {
        pos_0_reg_282 = ap_const_lv32_8;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        pos_0_reg_282 = pos_reg_706.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln529_fu_526_p2.read()))) {
        pos_1_reg_305 = pos_0_reg_282.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln537_fu_553_p2.read()))) {
        pos_1_reg_305 = pos_reg_706.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln531_fu_532_p2.read()))) {
        pos_2_reg_316 = pos_1_reg_305.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read()) && 
                esl_seteq<1,1,1>(ap_block_state15_on_subcall_done.read(), ap_const_boolean_0))) {
        pos_2_reg_316 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        r_0_i2_i_reg_223 = r_fu_433_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(icmp_ln417_fu_357_p2.read(), ap_const_lv1_0))) {
        r_0_i2_i_reg_223 = ap_const_lv64_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        signs_0_reg_247 = signs_fu_503_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(grp_keccak_squeezeblocks_1_fu_328_ap_done.read(), ap_const_logic_1))) {
        signs_0_reg_247 = ap_const_lv64_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln527_fu_509_p2.read()))) {
        signs_1_reg_294 = signs_0_reg_247.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        signs_1_reg_294 = signs_3_reg_730.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        add_ln417_reg_627 = add_ln417_fu_363_p2.read();
        zext_ln417_reg_619 = zext_ln417_fu_353_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln537_fu_553_p2.read()))) {
        c_coeffs_addr_1_reg_720 =  (sc_lv<8>) (zext_ln539_fu_559_p1.read());
        signs_3_reg_730 = signs_3_fu_578_p1.read();
        trunc_ln540_reg_725 = trunc_ln540_fu_564_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        i_33_reg_652 = i_33_fu_387_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        i_35_reg_735 = i_35_fu_587_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        i_reg_676 = i_fu_466_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        icmp_ln531_reg_702 = icmp_ln531_fu_532_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        pos_reg_706 = pos_fu_538_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln417_fu_357_p2.read(), ap_const_lv1_0))) {
        shl_ln_reg_632 = shl_ln_fu_373_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln30_fu_381_p2.read()))) {
        state_s_addr_12_reg_662 =  (sc_lv<5>) (zext_ln417_reg_619.read());
    }
}

void poly_challenge::thread_add_ln31_fu_397_p2() {
    add_ln31_fu_397_p2 = (!shl_ln_reg_632.read().is_01() || !zext_ln31_fu_393_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(shl_ln_reg_632.read()) + sc_biguint<5>(zext_ln31_fu_393_p1.read()));
}

void poly_challenge::thread_add_ln417_fu_363_p2() {
    add_ln417_fu_363_p2 = (!i_3_i_i_reg_200.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(i_3_i_i_reg_200.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void poly_challenge::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void poly_challenge::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void poly_challenge::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void poly_challenge::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void poly_challenge::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void poly_challenge::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void poly_challenge::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void poly_challenge::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void poly_challenge::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void poly_challenge::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void poly_challenge::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void poly_challenge::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void poly_challenge::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void poly_challenge::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void poly_challenge::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void poly_challenge::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void poly_challenge::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void poly_challenge::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void poly_challenge::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void poly_challenge::thread_ap_block_state15_on_subcall_done() {
    ap_block_state15_on_subcall_done = (esl_seteq<1,1,1>(ap_const_logic_0, grp_keccak_squeezeblocks_1_fu_328_ap_done.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read()));
}

void poly_challenge::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln529_fu_526_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void poly_challenge::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void poly_challenge::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln529_fu_526_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void poly_challenge::thread_buf_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        buf_address0 =  (sc_lv<8>) (zext_ln536_fu_544_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        buf_address0 =  (sc_lv<8>) (zext_ln524_fu_472_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        buf_address0 = grp_keccak_squeezeblocks_1_fu_328_out_r_address0.read();
    } else {
        buf_address0 = "XXXXXXXX";
    }
}

void poly_challenge::thread_buf_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        buf_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        buf_ce0 = grp_keccak_squeezeblocks_1_fu_328_out_r_ce0.read();
    } else {
        buf_ce0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_buf_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        buf_we0 = grp_keccak_squeezeblocks_1_fu_328_out_r_we0.read();
    } else {
        buf_we0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_c_coeffs_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        c_coeffs_address0 = c_coeffs_addr_1_reg_720.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        c_coeffs_address0 =  (sc_lv<8>) (zext_ln539_1_fu_582_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        c_coeffs_address0 =  (sc_lv<8>) (zext_ln539_fu_559_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c_coeffs_address0 =  (sc_lv<8>) (zext_ln528_fu_521_p1.read());
    } else {
        c_coeffs_address0 = "XXXXXXXX";
    }
}

void poly_challenge::thread_c_coeffs_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        c_coeffs_ce0 = ap_const_logic_1;
    } else {
        c_coeffs_ce0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_c_coeffs_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        c_coeffs_d0 = sext_ln540_fu_606_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        c_coeffs_d0 = c_coeffs_q0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        c_coeffs_d0 = ap_const_lv32_0;
    } else {
        c_coeffs_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void poly_challenge::thread_c_coeffs_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln527_fu_509_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read()))) {
        c_coeffs_we0 = ap_const_logic_1;
    } else {
        c_coeffs_we0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_grp_keccak_squeezeblocks_1_fu_328_ap_start() {
    grp_keccak_squeezeblocks_1_fu_328_ap_start = grp_keccak_squeezeblocks_1_fu_328_ap_start_reg.read();
}

void poly_challenge::thread_i_32_fu_342_p2() {
    i_32_fu_342_p2 = (!i_0_i_i_reg_189.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_i_i_reg_189.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void poly_challenge::thread_i_33_fu_387_p2() {
    i_33_fu_387_p2 = (!i_0_i1_i_reg_211.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_i1_i_reg_211.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void poly_challenge::thread_i_34_fu_515_p2() {
    i_34_fu_515_p2 = (!i_1_reg_259.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_1_reg_259.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void poly_challenge::thread_i_35_fu_587_p2() {
    i_35_fu_587_p2 = (!ap_const_lv9_1.is_01() || !i_2_reg_270.read().is_01())? sc_lv<9>(): (sc_biguint<9>(ap_const_lv9_1) + sc_biguint<9>(i_2_reg_270.read()));
}

void poly_challenge::thread_i_fu_466_p2() {
    i_fu_466_p2 = (!i_0_reg_235.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_0_reg_235.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void poly_challenge::thread_icmp_ln30_fu_381_p2() {
    icmp_ln30_fu_381_p2 = (!i_0_i1_i_reg_211.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i1_i_reg_211.read() == ap_const_lv4_8);
}

void poly_challenge::thread_icmp_ln362_fu_336_p2() {
    icmp_ln362_fu_336_p2 = (!i_0_i_i_reg_189.read().is_01() || !ap_const_lv5_19.is_01())? sc_lv<1>(): sc_lv<1>(i_0_i_i_reg_189.read() == ap_const_lv5_19);
}

void poly_challenge::thread_icmp_ln417_fu_357_p2() {
    icmp_ln417_fu_357_p2 = (!i_3_i_i_reg_200.read().is_01() || !ap_const_lv3_4.is_01())? sc_lv<1>(): sc_lv<1>(i_3_i_i_reg_200.read() == ap_const_lv3_4);
}

void poly_challenge::thread_icmp_ln523_fu_460_p2() {
    icmp_ln523_fu_460_p2 = (!i_0_reg_235.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_235.read() == ap_const_lv4_8);
}

void poly_challenge::thread_icmp_ln527_fu_509_p2() {
    icmp_ln527_fu_509_p2 = (!i_1_reg_259.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_259.read() == ap_const_lv9_100);
}

void poly_challenge::thread_icmp_ln529_fu_526_p2() {
    icmp_ln529_fu_526_p2 = (!i_2_reg_270.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_2_reg_270.read() == ap_const_lv9_100);
}

void poly_challenge::thread_icmp_ln531_fu_532_p2() {
    icmp_ln531_fu_532_p2 = (!pos_1_reg_305.read().is_01() || !ap_const_lv32_87.is_01())? sc_lv<1>(): (sc_biguint<32>(pos_1_reg_305.read()) > sc_biguint<32>(ap_const_lv32_87));
}

void poly_challenge::thread_icmp_ln537_fu_553_p2() {
    icmp_ln537_fu_553_p2 = (!zext_ln536_1_fu_549_p1.read().is_01() || !i_2_reg_270.read().is_01())? sc_lv<1>(): (sc_biguint<9>(zext_ln536_1_fu_549_p1.read()) > sc_biguint<9>(i_2_reg_270.read()));
}

void poly_challenge::thread_pos_fu_538_p2() {
    pos_fu_538_p2 = (!pos_2_reg_316.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(pos_2_reg_316.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void poly_challenge::thread_r_fu_433_p2() {
    r_fu_433_p2 = (shl_ln31_fu_427_p2.read() | r_0_i2_i_reg_223.read());
}

void poly_challenge::thread_seed_address0() {
    seed_address0 =  (sc_lv<13>) (zext_ln31_15_fu_402_p1.read());
}

void poly_challenge::thread_seed_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        seed_ce0 = ap_const_logic_1;
    } else {
        seed_ce0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_sext_ln540_fu_606_p1() {
    sext_ln540_fu_606_p1 = esl_sext<32,2>(sub_ln540_fu_600_p2.read());
}

void poly_challenge::thread_shl_ln15_fu_485_p3() {
    shl_ln15_fu_485_p3 = esl_concat<3,3>(trunc_ln524_fu_481_p1.read(), ap_const_lv3_0);
}

void poly_challenge::thread_shl_ln16_fu_415_p3() {
    shl_ln16_fu_415_p3 = esl_concat<3,3>(trunc_ln31_fu_411_p1.read(), ap_const_lv3_0);
}

void poly_challenge::thread_shl_ln17_fu_593_p3() {
    shl_ln17_fu_593_p3 = esl_concat<1,1>(trunc_ln540_reg_725.read(), ap_const_lv1_0);
}

void poly_challenge::thread_shl_ln31_fu_427_p2() {
    shl_ln31_fu_427_p2 = (!zext_ln31_17_fu_423_p1.read().is_01())? sc_lv<64>(): zext_ln31_16_fu_407_p1.read() << (unsigned short)zext_ln31_17_fu_423_p1.read().to_uint();
}

void poly_challenge::thread_shl_ln524_fu_497_p2() {
    shl_ln524_fu_497_p2 = (!zext_ln524_2_fu_493_p1.read().is_01())? sc_lv<64>(): zext_ln524_1_fu_477_p1.read() << (unsigned short)zext_ln524_2_fu_493_p1.read().to_uint();
}

void poly_challenge::thread_shl_ln_fu_373_p3() {
    shl_ln_fu_373_p3 = esl_concat<2,3>(trunc_ln418_fu_369_p1.read(), ap_const_lv3_0);
}

void poly_challenge::thread_signs_2_fu_568_p4() {
    signs_2_fu_568_p4 = signs_1_reg_294.read().range(63, 1);
}

void poly_challenge::thread_signs_3_fu_578_p1() {
    signs_3_fu_578_p1 = esl_zext<64,63>(signs_2_fu_568_p4.read());
}

void poly_challenge::thread_signs_fu_503_p2() {
    signs_fu_503_p2 = (shl_ln524_fu_497_p2.read() | signs_0_reg_247.read());
}

void poly_challenge::thread_state_s_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_address0 =  (sc_lv<5>) (ap_const_lv64_10);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_s_address0 = state_s_addr_12_reg_662.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_s_address0 =  (sc_lv<5>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_address0 =  (sc_lv<5>) (zext_ln363_fu_348_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_address0 = grp_keccak_squeezeblocks_1_fu_328_s_address0.read();
    } else {
        state_s_address0 =  (sc_lv<5>) ("XXXXX");
    }
}

void poly_challenge::thread_state_s_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_address1 =  (sc_lv<5>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        state_s_address1 =  (sc_lv<5>) (zext_ln417_reg_619.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        state_s_address1 =  (sc_lv<5>) (ap_const_lv64_10);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_address1 = grp_keccak_squeezeblocks_1_fu_328_s_address1.read();
    } else {
        state_s_address1 =  (sc_lv<5>) ("XXXXX");
    }
}

void poly_challenge::thread_state_s_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        state_s_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_ce0 = grp_keccak_squeezeblocks_1_fu_328_s_ce0.read();
    } else {
        state_s_ce0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_state_s_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        state_s_ce1 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_ce1 = grp_keccak_squeezeblocks_1_fu_328_s_ce1.read();
    } else {
        state_s_ce1 = ap_const_logic_0;
    }
}

void poly_challenge::thread_state_s_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_d0 = xor_ln452_fu_453_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        state_s_d0 = xor_ln418_fu_439_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        state_s_d0 = ap_const_lv64_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_d0 = grp_keccak_squeezeblocks_1_fu_328_s_d0.read();
    } else {
        state_s_d0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void poly_challenge::thread_state_s_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_d1 = xor_ln451_fu_446_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_d1 = grp_keccak_squeezeblocks_1_fu_328_s_d1.read();
    } else {
        state_s_d1 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void poly_challenge::thread_state_s_we0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln362_fu_336_p2.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        state_s_we0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_we0 = grp_keccak_squeezeblocks_1_fu_328_s_we0.read();
    } else {
        state_s_we0 = ap_const_logic_0;
    }
}

void poly_challenge::thread_state_s_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        state_s_we1 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln531_reg_702.read())))) {
        state_s_we1 = grp_keccak_squeezeblocks_1_fu_328_s_we1.read();
    } else {
        state_s_we1 = ap_const_logic_0;
    }
}

void poly_challenge::thread_sub_ln540_fu_600_p2() {
    sub_ln540_fu_600_p2 = (!ap_const_lv2_1.is_01() || !shl_ln17_fu_593_p3.read().is_01())? sc_lv<2>(): (sc_biguint<2>(ap_const_lv2_1) - sc_biguint<2>(shl_ln17_fu_593_p3.read()));
}

void poly_challenge::thread_trunc_ln31_fu_411_p1() {
    trunc_ln31_fu_411_p1 = i_0_i1_i_reg_211.read().range(3-1, 0);
}

void poly_challenge::thread_trunc_ln418_fu_369_p1() {
    trunc_ln418_fu_369_p1 = i_3_i_i_reg_200.read().range(2-1, 0);
}

void poly_challenge::thread_trunc_ln524_fu_481_p1() {
    trunc_ln524_fu_481_p1 = i_0_reg_235.read().range(3-1, 0);
}

void poly_challenge::thread_trunc_ln540_fu_564_p1() {
    trunc_ln540_fu_564_p1 = signs_1_reg_294.read().range(1-1, 0);
}

void poly_challenge::thread_xor_ln418_fu_439_p2() {
    xor_ln418_fu_439_p2 = (state_s_q1.read() ^ r_0_i2_i_reg_223.read());
}

void poly_challenge::thread_xor_ln451_fu_446_p2() {
    xor_ln451_fu_446_p2 = (state_s_q0.read() ^ ap_const_lv64_1F);
}

void poly_challenge::thread_xor_ln452_fu_453_p2() {
    xor_ln452_fu_453_p2 = (state_s_q1.read() ^ ap_const_lv64_8000000000000000);
}

void poly_challenge::thread_zext_ln31_15_fu_402_p1() {
    zext_ln31_15_fu_402_p1 = esl_zext<64,5>(add_ln31_fu_397_p2.read());
}

void poly_challenge::thread_zext_ln31_16_fu_407_p1() {
    zext_ln31_16_fu_407_p1 = esl_zext<64,8>(seed_q0.read());
}

void poly_challenge::thread_zext_ln31_17_fu_423_p1() {
    zext_ln31_17_fu_423_p1 = esl_zext<64,6>(shl_ln16_fu_415_p3.read());
}

void poly_challenge::thread_zext_ln31_fu_393_p1() {
    zext_ln31_fu_393_p1 = esl_zext<5,4>(i_0_i1_i_reg_211.read());
}

void poly_challenge::thread_zext_ln363_fu_348_p1() {
    zext_ln363_fu_348_p1 = esl_zext<64,5>(i_0_i_i_reg_189.read());
}

void poly_challenge::thread_zext_ln417_fu_353_p1() {
    zext_ln417_fu_353_p1 = esl_zext<64,3>(i_3_i_i_reg_200.read());
}

void poly_challenge::thread_zext_ln524_1_fu_477_p1() {
    zext_ln524_1_fu_477_p1 = esl_zext<64,8>(buf_q0.read());
}

void poly_challenge::thread_zext_ln524_2_fu_493_p1() {
    zext_ln524_2_fu_493_p1 = esl_zext<64,6>(shl_ln15_fu_485_p3.read());
}

void poly_challenge::thread_zext_ln524_fu_472_p1() {
    zext_ln524_fu_472_p1 = esl_zext<64,4>(i_0_reg_235.read());
}

void poly_challenge::thread_zext_ln528_fu_521_p1() {
    zext_ln528_fu_521_p1 = esl_zext<64,9>(i_1_reg_259.read());
}

void poly_challenge::thread_zext_ln536_1_fu_549_p1() {
    zext_ln536_1_fu_549_p1 = esl_zext<9,8>(buf_q0.read());
}

void poly_challenge::thread_zext_ln536_fu_544_p1() {
    zext_ln536_fu_544_p1 = esl_zext<64,32>(pos_2_reg_316.read());
}

void poly_challenge::thread_zext_ln539_1_fu_582_p1() {
    zext_ln539_1_fu_582_p1 = esl_zext<64,9>(i_2_reg_270.read());
}

void poly_challenge::thread_zext_ln539_fu_559_p1() {
    zext_ln539_fu_559_p1 = esl_zext<64,8>(buf_q0.read());
}

void poly_challenge::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln362_fu_336_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln417_fu_357_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln30_fu_381_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(grp_keccak_squeezeblocks_1_fu_328_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln523_fu_460_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state12;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 2048 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln527_fu_509_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state13;
            } else {
                ap_NS_fsm = ap_ST_fsm_state12;
            }
            break;
        case 4096 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, icmp_ln529_fu_526_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_block_state15_on_subcall_done.read(), ap_const_boolean_0))) {
                ap_NS_fsm = ap_ST_fsm_state16;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln537_fu_553_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state18;
            } else {
                ap_NS_fsm = ap_ST_fsm_state14;
            }
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<19>) ("XXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

