// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module pqcrystals_dilithium_2 (
        ap_ready,
        a,
        ap_return
);


output   ap_ready;
input  [31:0] a;
output  [31:0] ap_return;

wire   [31:0] add_ln36_fu_20_p2;
wire  signed [8:0] trunc_ln_fu_26_p4;
wire  signed [23:0] grp_fu_40_p1;
wire  signed [31:0] grp_fu_40_p3;

crypto_sign_mac_mhbi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 24 ),
    .din2_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
crypto_sign_mac_mhbi_U78(
    .din0(trunc_ln_fu_26_p4),
    .din1(grp_fu_40_p1),
    .din2(a),
    .dout(grp_fu_40_p3)
);

assign add_ln36_fu_20_p2 = (a + 32'd4194304);

assign ap_ready = 1'b1;

assign ap_return = grp_fu_40_p3;

assign grp_fu_40_p1 = 32'd4286586879;

assign trunc_ln_fu_26_p4 = {{add_ln36_fu_20_p2[31:23]}};

endmodule //pqcrystals_dilithium_2
